/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.disim.cacher.chains.ui.internal.ChainsActivator;

public class ChainsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ChainsActivator.getInstance().getInjector("org.xtext.disim.cacher.chains.Chains");
	}

}
