/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChainsRuntimeModule extends AbstractChainsRuntimeModule {
}
