/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ChainsStandaloneSetup extends ChainsStandaloneSetupGenerated {

	public static void doSetup() {
		new ChainsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
