/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CacherUiModule extends AbstractCacherUiModule {

	public CacherUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
