/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.disim.cacher.chains.chains.Chain;
import org.xtext.disim.cacher.chains.chains.ChainType;
import org.xtext.disim.cacher.chains.chains.ChainsPackage;
import org.xtext.disim.cacher.chains.chains.PromptChain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chain</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.impl.ChainImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.impl.ChainImpl#getChain <em>Chain</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.impl.ChainImpl#getChainType <em>Chain Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChainImpl extends MinimalEObjectImpl.Container implements Chain
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getChain() <em>Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChain()
   * @generated
   * @ordered
   */
  protected PromptChain chain;

  /**
   * The default value of the '{@link #getChainType() <em>Chain Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChainType()
   * @generated
   * @ordered
   */
  protected static final ChainType CHAIN_TYPE_EDEFAULT = ChainType.NONE;

  /**
   * The cached value of the '{@link #getChainType() <em>Chain Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChainType()
   * @generated
   * @ordered
   */
  protected ChainType chainType = CHAIN_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ChainsPackage.Literals.CHAIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChainsPackage.CHAIN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PromptChain getChain()
  {
    return chain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetChain(PromptChain newChain, NotificationChain msgs)
  {
    PromptChain oldChain = chain;
    chain = newChain;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ChainsPackage.CHAIN__CHAIN, oldChain, newChain);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChain(PromptChain newChain)
  {
    if (newChain != chain)
    {
      NotificationChain msgs = null;
      if (chain != null)
        msgs = ((InternalEObject)chain).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ChainsPackage.CHAIN__CHAIN, null, msgs);
      if (newChain != null)
        msgs = ((InternalEObject)newChain).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ChainsPackage.CHAIN__CHAIN, null, msgs);
      msgs = basicSetChain(newChain, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChainsPackage.CHAIN__CHAIN, newChain, newChain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ChainType getChainType()
  {
    return chainType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChainType(ChainType newChainType)
  {
    ChainType oldChainType = chainType;
    chainType = newChainType == null ? CHAIN_TYPE_EDEFAULT : newChainType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChainsPackage.CHAIN__CHAIN_TYPE, oldChainType, chainType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ChainsPackage.CHAIN__CHAIN:
        return basicSetChain(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ChainsPackage.CHAIN__NAME:
        return getName();
      case ChainsPackage.CHAIN__CHAIN:
        return getChain();
      case ChainsPackage.CHAIN__CHAIN_TYPE:
        return getChainType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ChainsPackage.CHAIN__NAME:
        setName((String)newValue);
        return;
      case ChainsPackage.CHAIN__CHAIN:
        setChain((PromptChain)newValue);
        return;
      case ChainsPackage.CHAIN__CHAIN_TYPE:
        setChainType((ChainType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ChainsPackage.CHAIN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ChainsPackage.CHAIN__CHAIN:
        setChain((PromptChain)null);
        return;
      case ChainsPackage.CHAIN__CHAIN_TYPE:
        setChainType(CHAIN_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ChainsPackage.CHAIN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ChainsPackage.CHAIN__CHAIN:
        return chain != null;
      case ChainsPackage.CHAIN__CHAIN_TYPE:
        return chainType != CHAIN_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", chainType: ");
    result.append(chainType);
    result.append(')');
    return result.toString();
  }

} //ChainImpl
