/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.disim.cacher.cacher.CacherPackage;

import org.xtext.disim.cacher.chains.chains.Chain;
import org.xtext.disim.cacher.chains.chains.ChainType;
import org.xtext.disim.cacher.chains.chains.ChainsFactory;
import org.xtext.disim.cacher.chains.chains.ChainsPackage;
import org.xtext.disim.cacher.chains.chains.PromptChain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ChainsPackageImpl extends EPackageImpl implements ChainsPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass chainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass promptChainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum chainTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ChainsPackageImpl()
  {
    super(eNS_URI, ChainsFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ChainsPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ChainsPackage init()
  {
    if (isInited) return (ChainsPackage)EPackage.Registry.INSTANCE.getEPackage(ChainsPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredChainsPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ChainsPackageImpl theChainsPackage = registeredChainsPackage instanceof ChainsPackageImpl ? (ChainsPackageImpl)registeredChainsPackage : new ChainsPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    CacherPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theChainsPackage.createPackageContents();

    // Initialize created meta-data
    theChainsPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theChainsPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ChainsPackage.eNS_URI, theChainsPackage);
    return theChainsPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getChain()
  {
    return chainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChain_Name()
  {
    return (EAttribute)chainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getChain_Chain()
  {
    return (EReference)chainEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getChain_ChainType()
  {
    return (EAttribute)chainEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPromptChain()
  {
    return promptChainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPromptChain_List()
  {
    return (EReference)promptChainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getChainType()
  {
    return chainTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ChainsFactory getChainsFactory()
  {
    return (ChainsFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    chainEClass = createEClass(CHAIN);
    createEAttribute(chainEClass, CHAIN__NAME);
    createEReference(chainEClass, CHAIN__CHAIN);
    createEAttribute(chainEClass, CHAIN__CHAIN_TYPE);

    promptChainEClass = createEClass(PROMPT_CHAIN);
    createEReference(promptChainEClass, PROMPT_CHAIN__LIST);

    // Create enums
    chainTypeEEnum = createEEnum(CHAIN_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    CacherPackage theCacherPackage = (CacherPackage)EPackage.Registry.INSTANCE.getEPackage(CacherPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(chainEClass, Chain.class, "Chain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getChain_Name(), ecorePackage.getEString(), "name", null, 0, 1, Chain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getChain_Chain(), this.getPromptChain(), null, "chain", null, 0, 1, Chain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChain_ChainType(), this.getChainType(), "chainType", null, 0, 1, Chain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(promptChainEClass, PromptChain.class, "PromptChain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPromptChain_List(), theCacherPackage.getExternalRef(), null, "list", null, 0, -1, PromptChain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(chainTypeEEnum, ChainType.class, "ChainType");
    addEEnumLiteral(chainTypeEEnum, ChainType.NONE);
    addEEnumLiteral(chainTypeEEnum, ChainType.NL);
    addEEnumLiteral(chainTypeEEnum, ChainType.TAG);

    // Create resource
    createResource(eNS_URI);
  }

} //ChainsPackageImpl
