/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.disim.cacher.chains.ide.contentassist.antlr.internal.InternalChainsParser;
import org.xtext.disim.cacher.chains.services.ChainsGrammarAccess;

public class ChainsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ChainsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ChainsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getChainTypeAccess().getAlternatives(), "rule__ChainType__Alternatives");
			builder.put(grammarAccess.getChainAccess().getGroup_0(), "rule__Chain__Group_0__0");
			builder.put(grammarAccess.getChainAccess().getGroup_1(), "rule__Chain__Group_1__0");
			builder.put(grammarAccess.getChainAccess().getGroup_1_0(), "rule__Chain__Group_1_0__0");
			builder.put(grammarAccess.getChainAccess().getGroup_1_1(), "rule__Chain__Group_1_1__0");
			builder.put(grammarAccess.getPromptChainAccess().getGroup(), "rule__PromptChain__Group__0");
			builder.put(grammarAccess.getPromptChainAccess().getGroup_1(), "rule__PromptChain__Group_1__0");
			builder.put(grammarAccess.getExternalRefParamAccess().getGroup(), "rule__ExternalRefParam__Group__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup(), "rule__ExternalRef__Group__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup_1(), "rule__ExternalRef__Group_1__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup_1_2(), "rule__ExternalRef__Group_1_2__0");
			builder.put(grammarAccess.getChainAccess().getNameAssignment_0_2(), "rule__Chain__NameAssignment_0_2");
			builder.put(grammarAccess.getChainAccess().getChainAssignment_1_0_4(), "rule__Chain__ChainAssignment_1_0_4");
			builder.put(grammarAccess.getChainAccess().getChainTypeAssignment_1_1_3(), "rule__Chain__ChainTypeAssignment_1_1_3");
			builder.put(grammarAccess.getPromptChainAccess().getListAssignment_0(), "rule__PromptChain__ListAssignment_0");
			builder.put(grammarAccess.getPromptChainAccess().getListAssignment_1_1(), "rule__PromptChain__ListAssignment_1_1");
			builder.put(grammarAccess.getExternalRefParamAccess().getPnameAssignment_0(), "rule__ExternalRefParam__PnameAssignment_0");
			builder.put(grammarAccess.getExternalRefParamAccess().getPvalAssignment_2(), "rule__ExternalRefParam__PvalAssignment_2");
			builder.put(grammarAccess.getExternalRefAccess().getPartAssignment_0(), "rule__ExternalRef__PartAssignment_0");
			builder.put(grammarAccess.getExternalRefAccess().getParamsAssignment_1_1(), "rule__ExternalRef__ParamsAssignment_1_1");
			builder.put(grammarAccess.getExternalRefAccess().getParamsAssignment_1_2_1(), "rule__ExternalRef__ParamsAssignment_1_2_1");
			builder.put(grammarAccess.getChainAccess().getUnorderedGroup(), "rule__Chain__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ChainsGrammarAccess grammarAccess;

	@Override
	protected InternalChainsParser createParser() {
		InternalChainsParser result = new InternalChainsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ChainsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ChainsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
