/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.disim.cacher.cacher.BodyParam;
import org.xtext.disim.cacher.cacher.BodyParamsList;
import org.xtext.disim.cacher.cacher.BodyPart;
import org.xtext.disim.cacher.cacher.CacherPackage;
import org.xtext.disim.cacher.cacher.Constraint;
import org.xtext.disim.cacher.cacher.ConstraintList;
import org.xtext.disim.cacher.cacher.Context;
import org.xtext.disim.cacher.cacher.ExternalRef;
import org.xtext.disim.cacher.cacher.ExternalRefParam;
import org.xtext.disim.cacher.cacher.OutputConstraint;
import org.xtext.disim.cacher.cacher.OutputConstraintList;
import org.xtext.disim.cacher.cacher.Prompt;
import org.xtext.disim.cacher.cacher.Request;
import org.xtext.disim.cacher.cacher.UsedPromptsList;
import org.xtext.disim.cacher.services.CacherGrammarAccess;

@SuppressWarnings("all")
public class CacherSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CacherGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CacherPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CacherPackage.BODY_PARAM:
				sequence_BodyParam(context, (BodyParam) semanticObject); 
				return; 
			case CacherPackage.BODY_PARAMS_LIST:
				sequence_BodyParamsList(context, (BodyParamsList) semanticObject); 
				return; 
			case CacherPackage.BODY_PART:
				sequence_BodyPart(context, (BodyPart) semanticObject); 
				return; 
			case CacherPackage.CONSTRAINT:
				sequence_Constraint(context, (Constraint) semanticObject); 
				return; 
			case CacherPackage.CONSTRAINT_LIST:
				sequence_ConstraintList(context, (ConstraintList) semanticObject); 
				return; 
			case CacherPackage.CONTEXT:
				sequence_Context(context, (Context) semanticObject); 
				return; 
			case CacherPackage.EXTERNAL_REF:
				sequence_ExternalRef(context, (ExternalRef) semanticObject); 
				return; 
			case CacherPackage.EXTERNAL_REF_PARAM:
				sequence_ExternalRefParam(context, (ExternalRefParam) semanticObject); 
				return; 
			case CacherPackage.OUTPUT_CONSTRAINT:
				sequence_OutputConstraint(context, (OutputConstraint) semanticObject); 
				return; 
			case CacherPackage.OUTPUT_CONSTRAINT_LIST:
				sequence_OutputConstraintList(context, (OutputConstraintList) semanticObject); 
				return; 
			case CacherPackage.PROMPT:
				sequence_Prompt(context, (Prompt) semanticObject); 
				return; 
			case CacherPackage.REQUEST:
				sequence_Request(context, (Request) semanticObject); 
				return; 
			case CacherPackage.USED_PROMPTS_LIST:
				sequence_UsedPromptsList(context, (UsedPromptsList) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     BodyParam returns BodyParam
	 *
	 * Constraint:
	 *     (name=ID def=STRING?)
	 * </pre>
	 */
	protected void sequence_BodyParam(ISerializationContext context, BodyParam semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     BodyParamsList returns BodyParamsList
	 *
	 * Constraint:
	 *     (list+=BodyParam list+=BodyParam*)
	 * </pre>
	 */
	protected void sequence_BodyParamsList(ISerializationContext context, BodyParamsList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     BodyPart returns BodyPart
	 *
	 * Constraint:
	 *     (content=STRING | param=[BodyParam|ID])
	 * </pre>
	 */
	protected void sequence_BodyPart(ISerializationContext context, BodyPart semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ConstraintList returns ConstraintList
	 *
	 * Constraint:
	 *     (list+=Constraint list+=Constraint*)
	 * </pre>
	 */
	protected void sequence_ConstraintList(ISerializationContext context, ConstraintList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Constraint returns Constraint
	 *
	 * Constraint:
	 *     (body+=BodyPart body+=BodyPart*)
	 * </pre>
	 */
	protected void sequence_Constraint(ISerializationContext context, Constraint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Context returns Context
	 *
	 * Constraint:
	 *     ((external+=ExternalRef external+=ExternalRef*) | body=STRING)
	 * </pre>
	 */
	protected void sequence_Context(ISerializationContext context, Context semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExternalRefParam returns ExternalRefParam
	 *
	 * Constraint:
	 *     (pname=ID pval=STRING)
	 * </pre>
	 */
	protected void sequence_ExternalRefParam(ISerializationContext context, ExternalRefParam semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PNAME));
			if (transientValues.isValueTransient(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PVAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PVAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExternalRefParamAccess().getPnameIDTerminalRuleCall_0_0(), semanticObject.getPname());
		feeder.accept(grammarAccess.getExternalRefParamAccess().getPvalSTRINGTerminalRuleCall_2_0(), semanticObject.getPval());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExternalRef returns ExternalRef
	 *
	 * Constraint:
	 *     (part=[Prompt|ID] (params+=ExternalRefParam params+=ExternalRefParam*)?)
	 * </pre>
	 */
	protected void sequence_ExternalRef(ISerializationContext context, ExternalRef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OutputConstraintList returns OutputConstraintList
	 *
	 * Constraint:
	 *     (list+=OutputConstraint list+=OutputConstraint*)
	 * </pre>
	 */
	protected void sequence_OutputConstraintList(ISerializationContext context, OutputConstraintList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OutputConstraint returns OutputConstraint
	 *
	 * Constraint:
	 *     (body+=BodyPart body+=BodyPart*)
	 * </pre>
	 */
	protected void sequence_OutputConstraint(ISerializationContext context, OutputConstraint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Prompt returns Prompt
	 *
	 * Constraint:
	 *     (
	 *         name=ID | 
	 *         usedPrompts=UsedPromptsList | 
	 *         bodyParams=BodyParamsList | 
	 *         context=Context | 
	 *         request=Request | 
	 *         posConst=ConstraintList | 
	 *         negConst=ConstraintList | 
	 *         dataPresent=OutputConstraintList | 
	 *         promptType=PromptType
	 *     )+
	 * </pre>
	 */
	protected void sequence_Prompt(ISerializationContext context, Prompt semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Request returns Request
	 *
	 * Constraint:
	 *     (body+=BodyPart body+=BodyPart*)
	 * </pre>
	 */
	protected void sequence_Request(ISerializationContext context, Request semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UsedPromptsList returns UsedPromptsList
	 *
	 * Constraint:
	 *     (list+=ExternalRef list+=ExternalRef*)
	 * </pre>
	 */
	protected void sequence_UsedPromptsList(ISerializationContext context, UsedPromptsList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
