/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChainsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/disim/cacher/chains/parser/antlr/internal/InternalChains.tokens");
	}
}
