/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.disim.cacher.chains.parser.antlr.internal.InternalChainsParser;
import org.xtext.disim.cacher.chains.services.ChainsGrammarAccess;

public class ChainsParser extends AbstractAntlrParser {

	@Inject
	private ChainsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalChainsParser createParser(XtextTokenStream stream) {
		return new InternalChainsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Chain";
	}

	public ChainsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ChainsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
