/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.disim.cacher.chains.ChainsRuntimeModule;
import org.xtext.disim.cacher.chains.ChainsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ChainsIdeSetup extends ChainsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ChainsRuntimeModule(), new ChainsIdeModule()));
	}
	
}
