/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.ide;


/**
 * Use this class to register ide components.
 */
public class ChainsIdeModule extends AbstractChainsIdeModule {
}
