/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.disim.cacher.parser.antlr.internal.InternalCacherParser;
import org.xtext.disim.cacher.services.CacherGrammarAccess;

public class CacherParser extends AbstractAntlrParser {

	@Inject
	private CacherGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCacherParser createParser(XtextTokenStream stream) {
		return new InternalCacherParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Prompt";
	}

	public CacherGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CacherGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
