/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CacherAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/disim/cacher/parser/antlr/internal/InternalCacher.tokens");
	}
}
