/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.disim.cacher.ui.internal.CacherActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CacherExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CacherActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CacherActivator activator = CacherActivator.getInstance();
		return activator != null ? activator.getInjector(CacherActivator.ORG_XTEXT_DISIM_CACHER_CACHER) : null;
	}

}
