/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCacherValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.disim.cacher.cacher.CacherPackage.eINSTANCE);
		return result;
	}
}
