/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.disim.cacher.cacher.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CacherFactoryImpl extends EFactoryImpl implements CacherFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CacherFactory init()
  {
    try
    {
      CacherFactory theCacherFactory = (CacherFactory)EPackage.Registry.INSTANCE.getEFactory(CacherPackage.eNS_URI);
      if (theCacherFactory != null)
      {
        return theCacherFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CacherFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CacherFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CacherPackage.PROMPT: return createPrompt();
      case CacherPackage.BODY_PARAMS_LIST: return createBodyParamsList();
      case CacherPackage.USED_PROMPTS_LIST: return createUsedPromptsList();
      case CacherPackage.CONTEXT: return createContext();
      case CacherPackage.REQUEST: return createRequest();
      case CacherPackage.CONSTRAINT_LIST: return createConstraintList();
      case CacherPackage.CONSTRAINT: return createConstraint();
      case CacherPackage.OUTPUT_CONSTRAINT_LIST: return createOutputConstraintList();
      case CacherPackage.OUTPUT_CONSTRAINT: return createOutputConstraint();
      case CacherPackage.EXTERNAL_REF_PARAM: return createExternalRefParam();
      case CacherPackage.EXTERNAL_REF: return createExternalRef();
      case CacherPackage.BODY_PARAM: return createBodyParam();
      case CacherPackage.BODY_PART: return createBodyPart();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CacherPackage.PROMPT_TYPE:
        return createPromptTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CacherPackage.PROMPT_TYPE:
        return convertPromptTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Prompt createPrompt()
  {
    PromptImpl prompt = new PromptImpl();
    return prompt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BodyParamsList createBodyParamsList()
  {
    BodyParamsListImpl bodyParamsList = new BodyParamsListImpl();
    return bodyParamsList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsedPromptsList createUsedPromptsList()
  {
    UsedPromptsListImpl usedPromptsList = new UsedPromptsListImpl();
    return usedPromptsList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Context createContext()
  {
    ContextImpl context = new ContextImpl();
    return context;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Request createRequest()
  {
    RequestImpl request = new RequestImpl();
    return request;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintList createConstraintList()
  {
    ConstraintListImpl constraintList = new ConstraintListImpl();
    return constraintList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Constraint createConstraint()
  {
    ConstraintImpl constraint = new ConstraintImpl();
    return constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutputConstraintList createOutputConstraintList()
  {
    OutputConstraintListImpl outputConstraintList = new OutputConstraintListImpl();
    return outputConstraintList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutputConstraint createOutputConstraint()
  {
    OutputConstraintImpl outputConstraint = new OutputConstraintImpl();
    return outputConstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExternalRefParam createExternalRefParam()
  {
    ExternalRefParamImpl externalRefParam = new ExternalRefParamImpl();
    return externalRefParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExternalRef createExternalRef()
  {
    ExternalRefImpl externalRef = new ExternalRefImpl();
    return externalRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BodyParam createBodyParam()
  {
    BodyParamImpl bodyParam = new BodyParamImpl();
    return bodyParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BodyPart createBodyPart()
  {
    BodyPartImpl bodyPart = new BodyPartImpl();
    return bodyPart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PromptType createPromptTypeFromString(EDataType eDataType, String initialValue)
  {
    PromptType result = PromptType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPromptTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CacherPackage getCacherPackage()
  {
    return (CacherPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CacherPackage getPackage()
  {
    return CacherPackage.eINSTANCE;
  }

} //CacherFactoryImpl
