/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.disim.cacher.cacher.CacherPackage;
import org.xtext.disim.cacher.cacher.ExternalRefParam;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External Ref Param</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl#getPname <em>Pname</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl#getPval <em>Pval</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExternalRefParamImpl extends MinimalEObjectImpl.Container implements ExternalRefParam
{
  /**
   * The default value of the '{@link #getPname() <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPname()
   * @generated
   * @ordered
   */
  protected static final String PNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPname() <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPname()
   * @generated
   * @ordered
   */
  protected String pname = PNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPval() <em>Pval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPval()
   * @generated
   * @ordered
   */
  protected static final String PVAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPval() <em>Pval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPval()
   * @generated
   * @ordered
   */
  protected String pval = PVAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalRefParamImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CacherPackage.Literals.EXTERNAL_REF_PARAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPname()
  {
    return pname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPname(String newPname)
  {
    String oldPname = pname;
    pname = newPname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.EXTERNAL_REF_PARAM__PNAME, oldPname, pname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPval()
  {
    return pval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPval(String newPval)
  {
    String oldPval = pval;
    pval = newPval;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.EXTERNAL_REF_PARAM__PVAL, oldPval, pval));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF_PARAM__PNAME:
        return getPname();
      case CacherPackage.EXTERNAL_REF_PARAM__PVAL:
        return getPval();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF_PARAM__PNAME:
        setPname((String)newValue);
        return;
      case CacherPackage.EXTERNAL_REF_PARAM__PVAL:
        setPval((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF_PARAM__PNAME:
        setPname(PNAME_EDEFAULT);
        return;
      case CacherPackage.EXTERNAL_REF_PARAM__PVAL:
        setPval(PVAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF_PARAM__PNAME:
        return PNAME_EDEFAULT == null ? pname != null : !PNAME_EDEFAULT.equals(pname);
      case CacherPackage.EXTERNAL_REF_PARAM__PVAL:
        return PVAL_EDEFAULT == null ? pval != null : !PVAL_EDEFAULT.equals(pval);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (pname: ");
    result.append(pname);
    result.append(", pval: ");
    result.append(pval);
    result.append(')');
    return result.toString();
  }

} //ExternalRefParamImpl
