/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.disim.cacher.cacher.CacherPackage;
import org.xtext.disim.cacher.cacher.ExternalRef;
import org.xtext.disim.cacher.cacher.ExternalRefParam;
import org.xtext.disim.cacher.cacher.Prompt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.ExternalRefImpl#getPart <em>Part</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.ExternalRefImpl#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExternalRefImpl extends MinimalEObjectImpl.Container implements ExternalRef
{
  /**
   * The cached value of the '{@link #getPart() <em>Part</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPart()
   * @generated
   * @ordered
   */
  protected Prompt part;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<ExternalRefParam> params;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CacherPackage.Literals.EXTERNAL_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Prompt getPart()
  {
    if (part != null && part.eIsProxy())
    {
      InternalEObject oldPart = (InternalEObject)part;
      part = (Prompt)eResolveProxy(oldPart);
      if (part != oldPart)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CacherPackage.EXTERNAL_REF__PART, oldPart, part));
      }
    }
    return part;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Prompt basicGetPart()
  {
    return part;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPart(Prompt newPart)
  {
    Prompt oldPart = part;
    part = newPart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.EXTERNAL_REF__PART, oldPart, part));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExternalRefParam> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<ExternalRefParam>(ExternalRefParam.class, this, CacherPackage.EXTERNAL_REF__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF__PART:
        if (resolve) return getPart();
        return basicGetPart();
      case CacherPackage.EXTERNAL_REF__PARAMS:
        return getParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF__PART:
        setPart((Prompt)newValue);
        return;
      case CacherPackage.EXTERNAL_REF__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends ExternalRefParam>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF__PART:
        setPart((Prompt)null);
        return;
      case CacherPackage.EXTERNAL_REF__PARAMS:
        getParams().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.EXTERNAL_REF__PART:
        return part != null;
      case CacherPackage.EXTERNAL_REF__PARAMS:
        return params != null && !params.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ExternalRefImpl
