/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.disim.cacher.cacher.BodyParamsList;
import org.xtext.disim.cacher.cacher.CacherPackage;
import org.xtext.disim.cacher.cacher.ConstraintList;
import org.xtext.disim.cacher.cacher.Context;
import org.xtext.disim.cacher.cacher.OutputConstraintList;
import org.xtext.disim.cacher.cacher.Prompt;
import org.xtext.disim.cacher.cacher.PromptType;
import org.xtext.disim.cacher.cacher.Request;
import org.xtext.disim.cacher.cacher.UsedPromptsList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prompt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getUsedPrompts <em>Used Prompts</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getBodyParams <em>Body Params</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getContext <em>Context</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getRequest <em>Request</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getPosConst <em>Pos Const</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getNegConst <em>Neg Const</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getDataPresent <em>Data Present</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.impl.PromptImpl#getPromptType <em>Prompt Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PromptImpl extends MinimalEObjectImpl.Container implements Prompt
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getUsedPrompts() <em>Used Prompts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsedPrompts()
   * @generated
   * @ordered
   */
  protected UsedPromptsList usedPrompts;

  /**
   * The cached value of the '{@link #getBodyParams() <em>Body Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBodyParams()
   * @generated
   * @ordered
   */
  protected BodyParamsList bodyParams;

  /**
   * The cached value of the '{@link #getContext() <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContext()
   * @generated
   * @ordered
   */
  protected Context context;

  /**
   * The cached value of the '{@link #getRequest() <em>Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequest()
   * @generated
   * @ordered
   */
  protected Request request;

  /**
   * The cached value of the '{@link #getPosConst() <em>Pos Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosConst()
   * @generated
   * @ordered
   */
  protected ConstraintList posConst;

  /**
   * The cached value of the '{@link #getNegConst() <em>Neg Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNegConst()
   * @generated
   * @ordered
   */
  protected ConstraintList negConst;

  /**
   * The cached value of the '{@link #getDataPresent() <em>Data Present</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataPresent()
   * @generated
   * @ordered
   */
  protected OutputConstraintList dataPresent;

  /**
   * The default value of the '{@link #getPromptType() <em>Prompt Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPromptType()
   * @generated
   * @ordered
   */
  protected static final PromptType PROMPT_TYPE_EDEFAULT = PromptType.NL;

  /**
   * The cached value of the '{@link #getPromptType() <em>Prompt Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPromptType()
   * @generated
   * @ordered
   */
  protected PromptType promptType = PROMPT_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PromptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CacherPackage.Literals.PROMPT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UsedPromptsList getUsedPrompts()
  {
    return usedPrompts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUsedPrompts(UsedPromptsList newUsedPrompts, NotificationChain msgs)
  {
    UsedPromptsList oldUsedPrompts = usedPrompts;
    usedPrompts = newUsedPrompts;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__USED_PROMPTS, oldUsedPrompts, newUsedPrompts);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUsedPrompts(UsedPromptsList newUsedPrompts)
  {
    if (newUsedPrompts != usedPrompts)
    {
      NotificationChain msgs = null;
      if (usedPrompts != null)
        msgs = ((InternalEObject)usedPrompts).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__USED_PROMPTS, null, msgs);
      if (newUsedPrompts != null)
        msgs = ((InternalEObject)newUsedPrompts).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__USED_PROMPTS, null, msgs);
      msgs = basicSetUsedPrompts(newUsedPrompts, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__USED_PROMPTS, newUsedPrompts, newUsedPrompts));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BodyParamsList getBodyParams()
  {
    return bodyParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBodyParams(BodyParamsList newBodyParams, NotificationChain msgs)
  {
    BodyParamsList oldBodyParams = bodyParams;
    bodyParams = newBodyParams;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__BODY_PARAMS, oldBodyParams, newBodyParams);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBodyParams(BodyParamsList newBodyParams)
  {
    if (newBodyParams != bodyParams)
    {
      NotificationChain msgs = null;
      if (bodyParams != null)
        msgs = ((InternalEObject)bodyParams).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__BODY_PARAMS, null, msgs);
      if (newBodyParams != null)
        msgs = ((InternalEObject)newBodyParams).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__BODY_PARAMS, null, msgs);
      msgs = basicSetBodyParams(newBodyParams, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__BODY_PARAMS, newBodyParams, newBodyParams));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Context getContext()
  {
    return context;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContext(Context newContext, NotificationChain msgs)
  {
    Context oldContext = context;
    context = newContext;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__CONTEXT, oldContext, newContext);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContext(Context newContext)
  {
    if (newContext != context)
    {
      NotificationChain msgs = null;
      if (context != null)
        msgs = ((InternalEObject)context).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__CONTEXT, null, msgs);
      if (newContext != null)
        msgs = ((InternalEObject)newContext).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__CONTEXT, null, msgs);
      msgs = basicSetContext(newContext, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__CONTEXT, newContext, newContext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Request getRequest()
  {
    return request;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRequest(Request newRequest, NotificationChain msgs)
  {
    Request oldRequest = request;
    request = newRequest;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__REQUEST, oldRequest, newRequest);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequest(Request newRequest)
  {
    if (newRequest != request)
    {
      NotificationChain msgs = null;
      if (request != null)
        msgs = ((InternalEObject)request).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__REQUEST, null, msgs);
      if (newRequest != null)
        msgs = ((InternalEObject)newRequest).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__REQUEST, null, msgs);
      msgs = basicSetRequest(newRequest, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__REQUEST, newRequest, newRequest));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintList getPosConst()
  {
    return posConst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPosConst(ConstraintList newPosConst, NotificationChain msgs)
  {
    ConstraintList oldPosConst = posConst;
    posConst = newPosConst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__POS_CONST, oldPosConst, newPosConst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPosConst(ConstraintList newPosConst)
  {
    if (newPosConst != posConst)
    {
      NotificationChain msgs = null;
      if (posConst != null)
        msgs = ((InternalEObject)posConst).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__POS_CONST, null, msgs);
      if (newPosConst != null)
        msgs = ((InternalEObject)newPosConst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__POS_CONST, null, msgs);
      msgs = basicSetPosConst(newPosConst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__POS_CONST, newPosConst, newPosConst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintList getNegConst()
  {
    return negConst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNegConst(ConstraintList newNegConst, NotificationChain msgs)
  {
    ConstraintList oldNegConst = negConst;
    negConst = newNegConst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__NEG_CONST, oldNegConst, newNegConst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNegConst(ConstraintList newNegConst)
  {
    if (newNegConst != negConst)
    {
      NotificationChain msgs = null;
      if (negConst != null)
        msgs = ((InternalEObject)negConst).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__NEG_CONST, null, msgs);
      if (newNegConst != null)
        msgs = ((InternalEObject)newNegConst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__NEG_CONST, null, msgs);
      msgs = basicSetNegConst(newNegConst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__NEG_CONST, newNegConst, newNegConst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutputConstraintList getDataPresent()
  {
    return dataPresent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDataPresent(OutputConstraintList newDataPresent, NotificationChain msgs)
  {
    OutputConstraintList oldDataPresent = dataPresent;
    dataPresent = newDataPresent;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__DATA_PRESENT, oldDataPresent, newDataPresent);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDataPresent(OutputConstraintList newDataPresent)
  {
    if (newDataPresent != dataPresent)
    {
      NotificationChain msgs = null;
      if (dataPresent != null)
        msgs = ((InternalEObject)dataPresent).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__DATA_PRESENT, null, msgs);
      if (newDataPresent != null)
        msgs = ((InternalEObject)newDataPresent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CacherPackage.PROMPT__DATA_PRESENT, null, msgs);
      msgs = basicSetDataPresent(newDataPresent, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__DATA_PRESENT, newDataPresent, newDataPresent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PromptType getPromptType()
  {
    return promptType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPromptType(PromptType newPromptType)
  {
    PromptType oldPromptType = promptType;
    promptType = newPromptType == null ? PROMPT_TYPE_EDEFAULT : newPromptType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CacherPackage.PROMPT__PROMPT_TYPE, oldPromptType, promptType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CacherPackage.PROMPT__USED_PROMPTS:
        return basicSetUsedPrompts(null, msgs);
      case CacherPackage.PROMPT__BODY_PARAMS:
        return basicSetBodyParams(null, msgs);
      case CacherPackage.PROMPT__CONTEXT:
        return basicSetContext(null, msgs);
      case CacherPackage.PROMPT__REQUEST:
        return basicSetRequest(null, msgs);
      case CacherPackage.PROMPT__POS_CONST:
        return basicSetPosConst(null, msgs);
      case CacherPackage.PROMPT__NEG_CONST:
        return basicSetNegConst(null, msgs);
      case CacherPackage.PROMPT__DATA_PRESENT:
        return basicSetDataPresent(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CacherPackage.PROMPT__NAME:
        return getName();
      case CacherPackage.PROMPT__USED_PROMPTS:
        return getUsedPrompts();
      case CacherPackage.PROMPT__BODY_PARAMS:
        return getBodyParams();
      case CacherPackage.PROMPT__CONTEXT:
        return getContext();
      case CacherPackage.PROMPT__REQUEST:
        return getRequest();
      case CacherPackage.PROMPT__POS_CONST:
        return getPosConst();
      case CacherPackage.PROMPT__NEG_CONST:
        return getNegConst();
      case CacherPackage.PROMPT__DATA_PRESENT:
        return getDataPresent();
      case CacherPackage.PROMPT__PROMPT_TYPE:
        return getPromptType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CacherPackage.PROMPT__NAME:
        setName((String)newValue);
        return;
      case CacherPackage.PROMPT__USED_PROMPTS:
        setUsedPrompts((UsedPromptsList)newValue);
        return;
      case CacherPackage.PROMPT__BODY_PARAMS:
        setBodyParams((BodyParamsList)newValue);
        return;
      case CacherPackage.PROMPT__CONTEXT:
        setContext((Context)newValue);
        return;
      case CacherPackage.PROMPT__REQUEST:
        setRequest((Request)newValue);
        return;
      case CacherPackage.PROMPT__POS_CONST:
        setPosConst((ConstraintList)newValue);
        return;
      case CacherPackage.PROMPT__NEG_CONST:
        setNegConst((ConstraintList)newValue);
        return;
      case CacherPackage.PROMPT__DATA_PRESENT:
        setDataPresent((OutputConstraintList)newValue);
        return;
      case CacherPackage.PROMPT__PROMPT_TYPE:
        setPromptType((PromptType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.PROMPT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CacherPackage.PROMPT__USED_PROMPTS:
        setUsedPrompts((UsedPromptsList)null);
        return;
      case CacherPackage.PROMPT__BODY_PARAMS:
        setBodyParams((BodyParamsList)null);
        return;
      case CacherPackage.PROMPT__CONTEXT:
        setContext((Context)null);
        return;
      case CacherPackage.PROMPT__REQUEST:
        setRequest((Request)null);
        return;
      case CacherPackage.PROMPT__POS_CONST:
        setPosConst((ConstraintList)null);
        return;
      case CacherPackage.PROMPT__NEG_CONST:
        setNegConst((ConstraintList)null);
        return;
      case CacherPackage.PROMPT__DATA_PRESENT:
        setDataPresent((OutputConstraintList)null);
        return;
      case CacherPackage.PROMPT__PROMPT_TYPE:
        setPromptType(PROMPT_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CacherPackage.PROMPT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CacherPackage.PROMPT__USED_PROMPTS:
        return usedPrompts != null;
      case CacherPackage.PROMPT__BODY_PARAMS:
        return bodyParams != null;
      case CacherPackage.PROMPT__CONTEXT:
        return context != null;
      case CacherPackage.PROMPT__REQUEST:
        return request != null;
      case CacherPackage.PROMPT__POS_CONST:
        return posConst != null;
      case CacherPackage.PROMPT__NEG_CONST:
        return negConst != null;
      case CacherPackage.PROMPT__DATA_PRESENT:
        return dataPresent != null;
      case CacherPackage.PROMPT__PROMPT_TYPE:
        return promptType != PROMPT_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", promptType: ");
    result.append(promptType);
    result.append(')');
    return result.toString();
  }

} //PromptImpl
