/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CacherGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PromptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.Prompt");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cThisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cIsKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cFullStopKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Keyword cUseKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cUsedPromptsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cUsedPromptsUsedPromptsListParserRuleCall_1_1_0 = (RuleCall)cUsedPromptsAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cUnorderedGroup.eContents().get(2);
		private final Keyword cAcceptsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cBodyParamsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cBodyParamsBodyParamsListParserRuleCall_2_1_0 = (RuleCall)cBodyParamsAssignment_2_1.eContents().get(0);
		private final Keyword cAsKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Keyword cParametersKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Keyword cFullStopKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Group cGroup_3 = (Group)cUnorderedGroup.eContents().get(3);
		private final Keyword cTheKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cGivenKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cContextKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Keyword cIsKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Assignment cContextAssignment_3_4 = (Assignment)cGroup_3.eContents().get(4);
		private final RuleCall cContextContextParserRuleCall_3_4_0 = (RuleCall)cContextAssignment_3_4.eContents().get(0);
		private final Group cGroup_4 = (Group)cUnorderedGroup.eContents().get(4);
		private final Keyword cMyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cProblemKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Keyword cIsKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cRequestAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cRequestRequestParserRuleCall_4_3_0 = (RuleCall)cRequestAssignment_4_3.eContents().get(0);
		private final Group cGroup_5 = (Group)cUnorderedGroup.eContents().get(5);
		private final Keyword cYouKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cMustKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cColonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cPosConstAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cPosConstConstraintListParserRuleCall_5_3_0 = (RuleCall)cPosConstAssignment_5_3.eContents().get(0);
		private final Group cGroup_6 = (Group)cUnorderedGroup.eContents().get(6);
		private final Keyword cYouKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cMustKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cNotKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Keyword cColonKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Assignment cNegConstAssignment_6_4 = (Assignment)cGroup_6.eContents().get(4);
		private final RuleCall cNegConstConstraintListParserRuleCall_6_4_0 = (RuleCall)cNegConstAssignment_6_4.eContents().get(0);
		private final Group cGroup_7 = (Group)cUnorderedGroup.eContents().get(7);
		private final Keyword cTheKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cOutputKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cMustKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Keyword cColonKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Assignment cDataPresentAssignment_7_4 = (Assignment)cGroup_7.eContents().get(4);
		private final RuleCall cDataPresentOutputConstraintListParserRuleCall_7_4_0 = (RuleCall)cDataPresentAssignment_7_4.eContents().get(0);
		private final Group cGroup_8 = (Group)cUnorderedGroup.eContents().get(8);
		private final Keyword cGenerateKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cAKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cPromptTypeAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cPromptTypePromptTypeEnumRuleCall_8_2_0 = (RuleCall)cPromptTypeAssignment_8_2.eContents().get(0);
		private final Keyword cPromptKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Keyword cFullStopKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		
		//Prompt:
		//    ('This' 'is' name=ID '.')? &
		//    ('Use' usedPrompts=UsedPromptsList)? &
		//    ('Accepts' bodyParams=BodyParamsList 'as' 'parameters' '.')? &
		//    ('The' 'given' 'context' 'is' context=Context)? &
		//    ('My' 'problem' 'is' request=Request) &
		//    ('You' 'must' ':' posConst=ConstraintList)? &
		//    ('You' 'must' 'not' ':' negConst=ConstraintList)? &
		//    ('The' 'output' 'must' ':' dataPresent=OutputConstraintList)? &
		//    ('Generate' 'a' promptType=PromptType 'prompt' '.')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('This' 'is' name=ID '.')? &
		//('Use' usedPrompts=UsedPromptsList)? &
		//('Accepts' bodyParams=BodyParamsList 'as' 'parameters' '.')? &
		//('The' 'given' 'context' 'is' context=Context)? &
		//('My' 'problem' 'is' request=Request) &
		//('You' 'must' ':' posConst=ConstraintList)? &
		//('You' 'must' 'not' ':' negConst=ConstraintList)? &
		//('The' 'output' 'must' ':' dataPresent=OutputConstraintList)? &
		//('Generate' 'a' promptType=PromptType 'prompt' '.')?
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//('This' 'is' name=ID '.')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'This'
		public Keyword getThisKeyword_0_0() { return cThisKeyword_0_0; }
		
		//'is'
		public Keyword getIsKeyword_0_1() { return cIsKeyword_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }
		
		//'.'
		public Keyword getFullStopKeyword_0_3() { return cFullStopKeyword_0_3; }
		
		//('Use' usedPrompts=UsedPromptsList)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'Use'
		public Keyword getUseKeyword_1_0() { return cUseKeyword_1_0; }
		
		//usedPrompts=UsedPromptsList
		public Assignment getUsedPromptsAssignment_1_1() { return cUsedPromptsAssignment_1_1; }
		
		//UsedPromptsList
		public RuleCall getUsedPromptsUsedPromptsListParserRuleCall_1_1_0() { return cUsedPromptsUsedPromptsListParserRuleCall_1_1_0; }
		
		//('Accepts' bodyParams=BodyParamsList 'as' 'parameters' '.')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Accepts'
		public Keyword getAcceptsKeyword_2_0() { return cAcceptsKeyword_2_0; }
		
		//bodyParams=BodyParamsList
		public Assignment getBodyParamsAssignment_2_1() { return cBodyParamsAssignment_2_1; }
		
		//BodyParamsList
		public RuleCall getBodyParamsBodyParamsListParserRuleCall_2_1_0() { return cBodyParamsBodyParamsListParserRuleCall_2_1_0; }
		
		//'as'
		public Keyword getAsKeyword_2_2() { return cAsKeyword_2_2; }
		
		//'parameters'
		public Keyword getParametersKeyword_2_3() { return cParametersKeyword_2_3; }
		
		//'.'
		public Keyword getFullStopKeyword_2_4() { return cFullStopKeyword_2_4; }
		
		//('The' 'given' 'context' 'is' context=Context)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'The'
		public Keyword getTheKeyword_3_0() { return cTheKeyword_3_0; }
		
		//'given'
		public Keyword getGivenKeyword_3_1() { return cGivenKeyword_3_1; }
		
		//'context'
		public Keyword getContextKeyword_3_2() { return cContextKeyword_3_2; }
		
		//'is'
		public Keyword getIsKeyword_3_3() { return cIsKeyword_3_3; }
		
		//context=Context
		public Assignment getContextAssignment_3_4() { return cContextAssignment_3_4; }
		
		//Context
		public RuleCall getContextContextParserRuleCall_3_4_0() { return cContextContextParserRuleCall_3_4_0; }
		
		//('My' 'problem' 'is' request=Request)
		public Group getGroup_4() { return cGroup_4; }
		
		//'My'
		public Keyword getMyKeyword_4_0() { return cMyKeyword_4_0; }
		
		//'problem'
		public Keyword getProblemKeyword_4_1() { return cProblemKeyword_4_1; }
		
		//'is'
		public Keyword getIsKeyword_4_2() { return cIsKeyword_4_2; }
		
		//request=Request
		public Assignment getRequestAssignment_4_3() { return cRequestAssignment_4_3; }
		
		//Request
		public RuleCall getRequestRequestParserRuleCall_4_3_0() { return cRequestRequestParserRuleCall_4_3_0; }
		
		//('You' 'must' ':' posConst=ConstraintList)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'You'
		public Keyword getYouKeyword_5_0() { return cYouKeyword_5_0; }
		
		//'must'
		public Keyword getMustKeyword_5_1() { return cMustKeyword_5_1; }
		
		//':'
		public Keyword getColonKeyword_5_2() { return cColonKeyword_5_2; }
		
		//posConst=ConstraintList
		public Assignment getPosConstAssignment_5_3() { return cPosConstAssignment_5_3; }
		
		//ConstraintList
		public RuleCall getPosConstConstraintListParserRuleCall_5_3_0() { return cPosConstConstraintListParserRuleCall_5_3_0; }
		
		//('You' 'must' 'not' ':' negConst=ConstraintList)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'You'
		public Keyword getYouKeyword_6_0() { return cYouKeyword_6_0; }
		
		//'must'
		public Keyword getMustKeyword_6_1() { return cMustKeyword_6_1; }
		
		//'not'
		public Keyword getNotKeyword_6_2() { return cNotKeyword_6_2; }
		
		//':'
		public Keyword getColonKeyword_6_3() { return cColonKeyword_6_3; }
		
		//negConst=ConstraintList
		public Assignment getNegConstAssignment_6_4() { return cNegConstAssignment_6_4; }
		
		//ConstraintList
		public RuleCall getNegConstConstraintListParserRuleCall_6_4_0() { return cNegConstConstraintListParserRuleCall_6_4_0; }
		
		//('The' 'output' 'must' ':' dataPresent=OutputConstraintList)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'The'
		public Keyword getTheKeyword_7_0() { return cTheKeyword_7_0; }
		
		//'output'
		public Keyword getOutputKeyword_7_1() { return cOutputKeyword_7_1; }
		
		//'must'
		public Keyword getMustKeyword_7_2() { return cMustKeyword_7_2; }
		
		//':'
		public Keyword getColonKeyword_7_3() { return cColonKeyword_7_3; }
		
		//dataPresent=OutputConstraintList
		public Assignment getDataPresentAssignment_7_4() { return cDataPresentAssignment_7_4; }
		
		//OutputConstraintList
		public RuleCall getDataPresentOutputConstraintListParserRuleCall_7_4_0() { return cDataPresentOutputConstraintListParserRuleCall_7_4_0; }
		
		//('Generate' 'a' promptType=PromptType 'prompt' '.')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'Generate'
		public Keyword getGenerateKeyword_8_0() { return cGenerateKeyword_8_0; }
		
		//'a'
		public Keyword getAKeyword_8_1() { return cAKeyword_8_1; }
		
		//promptType=PromptType
		public Assignment getPromptTypeAssignment_8_2() { return cPromptTypeAssignment_8_2; }
		
		//PromptType
		public RuleCall getPromptTypePromptTypeEnumRuleCall_8_2_0() { return cPromptTypePromptTypeEnumRuleCall_8_2_0; }
		
		//'prompt'
		public Keyword getPromptKeyword_8_3() { return cPromptKeyword_8_3; }
		
		//'.'
		public Keyword getFullStopKeyword_8_4() { return cFullStopKeyword_8_4; }
	}
	public class BodyParamsListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.BodyParamsList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cListBodyParamParserRuleCall_0_0 = (RuleCall)cListAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cListAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cListBodyParamParserRuleCall_1_1_0 = (RuleCall)cListAssignment_1_1.eContents().get(0);
		
		//BodyParamsList:
		//    list+=BodyParam (',' list+=BodyParam)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//list+=BodyParam (',' list+=BodyParam)*
		public Group getGroup() { return cGroup; }
		
		//list+=BodyParam
		public Assignment getListAssignment_0() { return cListAssignment_0; }
		
		//BodyParam
		public RuleCall getListBodyParamParserRuleCall_0_0() { return cListBodyParamParserRuleCall_0_0; }
		
		//(',' list+=BodyParam)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//list+=BodyParam
		public Assignment getListAssignment_1_1() { return cListAssignment_1_1; }
		
		//BodyParam
		public RuleCall getListBodyParamParserRuleCall_1_1_0() { return cListBodyParamParserRuleCall_1_1_0; }
	}
	public class UsedPromptsListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.UsedPromptsList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cListExternalRefParserRuleCall_0_0 = (RuleCall)cListAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cListAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cListExternalRefParserRuleCall_1_1_0 = (RuleCall)cListAssignment_1_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//UsedPromptsList:
		//    list+=ExternalRef (',' list+=ExternalRef)* '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//list+=ExternalRef (',' list+=ExternalRef)* '.'
		public Group getGroup() { return cGroup; }
		
		//list+=ExternalRef
		public Assignment getListAssignment_0() { return cListAssignment_0; }
		
		//ExternalRef
		public RuleCall getListExternalRefParserRuleCall_0_0() { return cListExternalRefParserRuleCall_0_0; }
		
		//(',' list+=ExternalRef)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//list+=ExternalRef
		public Assignment getListAssignment_1_1() { return cListAssignment_1_1; }
		
		//ExternalRef
		public RuleCall getListExternalRefParserRuleCall_1_1_0() { return cListExternalRefParserRuleCall_1_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}
	public class ContextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.Context");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Assignment cExternalAssignment_0_0_0 = (Assignment)cGroup_0_0.eContents().get(0);
		private final RuleCall cExternalExternalRefParserRuleCall_0_0_0_0 = (RuleCall)cExternalAssignment_0_0_0.eContents().get(0);
		private final Group cGroup_0_0_1 = (Group)cGroup_0_0.eContents().get(1);
		private final Keyword cAndKeyword_0_0_1_0 = (Keyword)cGroup_0_0_1.eContents().get(0);
		private final Assignment cExternalAssignment_0_0_1_1 = (Assignment)cGroup_0_0_1.eContents().get(1);
		private final RuleCall cExternalExternalRefParserRuleCall_0_0_1_1_0 = (RuleCall)cExternalAssignment_0_0_1_1.eContents().get(0);
		private final Assignment cBodyAssignment_0_1 = (Assignment)cAlternatives_0.eContents().get(1);
		private final RuleCall cBodySTRINGTerminalRuleCall_0_1_0 = (RuleCall)cBodyAssignment_0_1.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Context:
		//    (external+=ExternalRef ('and' external+=ExternalRef)* | body=STRING) '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(external+=ExternalRef ('and' external+=ExternalRef)* | body=STRING) '.'
		public Group getGroup() { return cGroup; }
		
		//(external+=ExternalRef ('and' external+=ExternalRef)* | body=STRING)
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//external+=ExternalRef ('and' external+=ExternalRef)*
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//external+=ExternalRef
		public Assignment getExternalAssignment_0_0_0() { return cExternalAssignment_0_0_0; }
		
		//ExternalRef
		public RuleCall getExternalExternalRefParserRuleCall_0_0_0_0() { return cExternalExternalRefParserRuleCall_0_0_0_0; }
		
		//('and' external+=ExternalRef)*
		public Group getGroup_0_0_1() { return cGroup_0_0_1; }
		
		//'and'
		public Keyword getAndKeyword_0_0_1_0() { return cAndKeyword_0_0_1_0; }
		
		//external+=ExternalRef
		public Assignment getExternalAssignment_0_0_1_1() { return cExternalAssignment_0_0_1_1; }
		
		//ExternalRef
		public RuleCall getExternalExternalRefParserRuleCall_0_0_1_1_0() { return cExternalExternalRefParserRuleCall_0_0_1_1_0; }
		
		//body=STRING
		public Assignment getBodyAssignment_0_1() { return cBodyAssignment_0_1; }
		
		//STRING
		public RuleCall getBodySTRINGTerminalRuleCall_0_1_0() { return cBodySTRINGTerminalRuleCall_0_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
	}
	public class RequestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.Request");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBodyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBodyBodyPartParserRuleCall_0_0 = (RuleCall)cBodyAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cBodyAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cBodyBodyPartParserRuleCall_1_1_0 = (RuleCall)cBodyAssignment_1_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Request:
		//    body+=BodyPart (',' body+=BodyPart)* '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//body+=BodyPart (',' body+=BodyPart)* '.'
		public Group getGroup() { return cGroup; }
		
		//body+=BodyPart
		public Assignment getBodyAssignment_0() { return cBodyAssignment_0; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_0_0() { return cBodyBodyPartParserRuleCall_0_0; }
		
		//(',' body+=BodyPart)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//body+=BodyPart
		public Assignment getBodyAssignment_1_1() { return cBodyAssignment_1_1; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_1_1_0() { return cBodyBodyPartParserRuleCall_1_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}
	public class ConstraintListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.ConstraintList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cListConstraintParserRuleCall_0_0 = (RuleCall)cListAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cListAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cListConstraintParserRuleCall_1_1_0 = (RuleCall)cListAssignment_1_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ConstraintList:
		//    list+=Constraint (';' list+=Constraint)* '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//list+=Constraint (';' list+=Constraint)* '.'
		public Group getGroup() { return cGroup; }
		
		//list+=Constraint
		public Assignment getListAssignment_0() { return cListAssignment_0; }
		
		//Constraint
		public RuleCall getListConstraintParserRuleCall_0_0() { return cListConstraintParserRuleCall_0_0; }
		
		//(';' list+=Constraint)*
		public Group getGroup_1() { return cGroup_1; }
		
		//';'
		public Keyword getSemicolonKeyword_1_0() { return cSemicolonKeyword_1_0; }
		
		//list+=Constraint
		public Assignment getListAssignment_1_1() { return cListAssignment_1_1; }
		
		//Constraint
		public RuleCall getListConstraintParserRuleCall_1_1_0() { return cListConstraintParserRuleCall_1_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}
	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBodyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBodyBodyPartParserRuleCall_0_0 = (RuleCall)cBodyAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cBodyAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cBodyBodyPartParserRuleCall_1_1_0 = (RuleCall)cBodyAssignment_1_1.eContents().get(0);
		
		//Constraint:
		//    //body=STRING
		//    body+=BodyPart (',' body+=BodyPart)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////body=STRING
		//body+=BodyPart (',' body+=BodyPart)*
		public Group getGroup() { return cGroup; }
		
		////body=STRING
		//body+=BodyPart
		public Assignment getBodyAssignment_0() { return cBodyAssignment_0; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_0_0() { return cBodyBodyPartParserRuleCall_0_0; }
		
		//(',' body+=BodyPart)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//body+=BodyPart
		public Assignment getBodyAssignment_1_1() { return cBodyAssignment_1_1; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_1_1_0() { return cBodyBodyPartParserRuleCall_1_1_0; }
	}
	public class OutputConstraintListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.OutputConstraintList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cListOutputConstraintParserRuleCall_0_0 = (RuleCall)cListAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cListAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cListOutputConstraintParserRuleCall_1_1_0 = (RuleCall)cListAssignment_1_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//OutputConstraintList:
		//    list+=OutputConstraint (';' list+=OutputConstraint)* '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//list+=OutputConstraint (';' list+=OutputConstraint)* '.'
		public Group getGroup() { return cGroup; }
		
		//list+=OutputConstraint
		public Assignment getListAssignment_0() { return cListAssignment_0; }
		
		//OutputConstraint
		public RuleCall getListOutputConstraintParserRuleCall_0_0() { return cListOutputConstraintParserRuleCall_0_0; }
		
		//(';' list+=OutputConstraint)*
		public Group getGroup_1() { return cGroup_1; }
		
		//';'
		public Keyword getSemicolonKeyword_1_0() { return cSemicolonKeyword_1_0; }
		
		//list+=OutputConstraint
		public Assignment getListAssignment_1_1() { return cListAssignment_1_1; }
		
		//OutputConstraint
		public RuleCall getListOutputConstraintParserRuleCall_1_1_0() { return cListOutputConstraintParserRuleCall_1_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}
	public class OutputConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.OutputConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBodyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBodyBodyPartParserRuleCall_0_0 = (RuleCall)cBodyAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cBodyAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cBodyBodyPartParserRuleCall_1_1_0 = (RuleCall)cBodyAssignment_1_1.eContents().get(0);
		
		//OutputConstraint:
		//    //body=STRING
		//    body+=BodyPart (',' body+=BodyPart)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////body=STRING
		//body+=BodyPart (',' body+=BodyPart)*
		public Group getGroup() { return cGroup; }
		
		////body=STRING
		//body+=BodyPart
		public Assignment getBodyAssignment_0() { return cBodyAssignment_0; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_0_0() { return cBodyBodyPartParserRuleCall_0_0; }
		
		//(',' body+=BodyPart)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//body+=BodyPart
		public Assignment getBodyAssignment_1_1() { return cBodyAssignment_1_1; }
		
		//BodyPart
		public RuleCall getBodyBodyPartParserRuleCall_1_1_0() { return cBodyBodyPartParserRuleCall_1_1_0; }
	}
	public class ExternalRefParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.ExternalRefParam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPnameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPnameIDTerminalRuleCall_0_0 = (RuleCall)cPnameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPvalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPvalSTRINGTerminalRuleCall_2_0 = (RuleCall)cPvalAssignment_2.eContents().get(0);
		
		///* My external refs */
		//ExternalRefParam:
		//    pname=ID '=' pval=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//pname=ID '=' pval=STRING
		public Group getGroup() { return cGroup; }
		
		//pname=ID
		public Assignment getPnameAssignment_0() { return cPnameAssignment_0; }
		
		//ID
		public RuleCall getPnameIDTerminalRuleCall_0_0() { return cPnameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//pval=STRING
		public Assignment getPvalAssignment_2() { return cPvalAssignment_2; }
		
		//STRING
		public RuleCall getPvalSTRINGTerminalRuleCall_2_0() { return cPvalSTRINGTerminalRuleCall_2_0; }
	}
	public class ExternalRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.ExternalRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPartAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPartPromptCrossReference_0_0 = (CrossReference)cPartAssignment_0.eContents().get(0);
		private final RuleCall cPartPromptIDTerminalRuleCall_0_0_1 = (RuleCall)cPartPromptCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cParamsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cParamsExternalRefParamParserRuleCall_1_1_0 = (RuleCall)cParamsAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cParamsAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cParamsExternalRefParamParserRuleCall_1_2_1_0 = (RuleCall)cParamsAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//ExternalRef:
		//    part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		public Group getGroup() { return cGroup; }
		
		//part=[Prompt]
		public Assignment getPartAssignment_0() { return cPartAssignment_0; }
		
		//[Prompt]
		public CrossReference getPartPromptCrossReference_0_0() { return cPartPromptCrossReference_0_0; }
		
		//ID
		public RuleCall getPartPromptIDTerminalRuleCall_0_0_1() { return cPartPromptIDTerminalRuleCall_0_0_1; }
		
		//('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//params+=ExternalRefParam
		public Assignment getParamsAssignment_1_1() { return cParamsAssignment_1_1; }
		
		//ExternalRefParam
		public RuleCall getParamsExternalRefParamParserRuleCall_1_1_0() { return cParamsExternalRefParamParserRuleCall_1_1_0; }
		
		//(',' params+=ExternalRefParam)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//params+=ExternalRefParam
		public Assignment getParamsAssignment_1_2_1() { return cParamsAssignment_1_2_1; }
		
		//ExternalRefParam
		public RuleCall getParamsExternalRefParamParserRuleCall_1_2_1_0() { return cParamsExternalRefParamParserRuleCall_1_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	public class BodyParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.BodyParam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDefAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDefSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cDefAssignment_1_1.eContents().get(0);
		
		///* My body parts */
		//BodyParam:
		//    name=ID ('=' def=STRING)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('=' def=STRING)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('=' def=STRING)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_0() { return cEqualsSignKeyword_1_0; }
		
		//def=STRING
		public Assignment getDefAssignment_1_1() { return cDefAssignment_1_1; }
		
		//STRING
		public RuleCall getDefSTRINGTerminalRuleCall_1_1_0() { return cDefSTRINGTerminalRuleCall_1_1_0; }
	}
	public class BodyPartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.BodyPart");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cContentAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cContentSTRINGTerminalRuleCall_0_0 = (RuleCall)cContentAssignment_0.eContents().get(0);
		private final Assignment cParamAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final CrossReference cParamBodyParamCrossReference_1_0 = (CrossReference)cParamAssignment_1.eContents().get(0);
		private final RuleCall cParamBodyParamIDTerminalRuleCall_1_0_1 = (RuleCall)cParamBodyParamCrossReference_1_0.eContents().get(1);
		
		//BodyPart:
		//    content=STRING |
		//    param=[BodyParam]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//content=STRING |
		//param=[BodyParam]
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//content=STRING
		public Assignment getContentAssignment_0() { return cContentAssignment_0; }
		
		//STRING
		public RuleCall getContentSTRINGTerminalRuleCall_0_0() { return cContentSTRINGTerminalRuleCall_0_0; }
		
		//param=[BodyParam]
		public Assignment getParamAssignment_1() { return cParamAssignment_1; }
		
		//[BodyParam]
		public CrossReference getParamBodyParamCrossReference_1_0() { return cParamBodyParamCrossReference_1_0; }
		
		//ID
		public RuleCall getParamBodyParamIDTerminalRuleCall_1_0_1() { return cParamBodyParamIDTerminalRuleCall_1_0_1; }
	}
	
	public class PromptTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.Cacher.PromptType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNLEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNLNaturalLanguageKeyword_0_0 = (Keyword)cNLEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTAGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTAGTagBasedKeyword_1_0 = (Keyword)cTAGEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum PromptType:
		//    NL='natural language' | TAG='tag based'
		//;
		public EnumRule getRule() { return rule; }
		
		//NL='natural language' | TAG='tag based'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NL='natural language'
		public EnumLiteralDeclaration getNLEnumLiteralDeclaration_0() { return cNLEnumLiteralDeclaration_0; }
		
		//'natural language'
		public Keyword getNLNaturalLanguageKeyword_0_0() { return cNLNaturalLanguageKeyword_0_0; }
		
		//TAG='tag based'
		public EnumLiteralDeclaration getTAGEnumLiteralDeclaration_1() { return cTAGEnumLiteralDeclaration_1; }
		
		//'tag based'
		public Keyword getTAGTagBasedKeyword_1_0() { return cTAGTagBasedKeyword_1_0; }
	}
	
	private final PromptElements pPrompt;
	private final BodyParamsListElements pBodyParamsList;
	private final UsedPromptsListElements pUsedPromptsList;
	private final ContextElements pContext;
	private final RequestElements pRequest;
	private final ConstraintListElements pConstraintList;
	private final ConstraintElements pConstraint;
	private final OutputConstraintListElements pOutputConstraintList;
	private final OutputConstraintElements pOutputConstraint;
	private final ExternalRefParamElements pExternalRefParam;
	private final ExternalRefElements pExternalRef;
	private final BodyParamElements pBodyParam;
	private final BodyPartElements pBodyPart;
	private final PromptTypeElements ePromptType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CacherGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPrompt = new PromptElements();
		this.pBodyParamsList = new BodyParamsListElements();
		this.pUsedPromptsList = new UsedPromptsListElements();
		this.pContext = new ContextElements();
		this.pRequest = new RequestElements();
		this.pConstraintList = new ConstraintListElements();
		this.pConstraint = new ConstraintElements();
		this.pOutputConstraintList = new OutputConstraintListElements();
		this.pOutputConstraint = new OutputConstraintElements();
		this.pExternalRefParam = new ExternalRefParamElements();
		this.pExternalRef = new ExternalRefElements();
		this.pBodyParam = new BodyParamElements();
		this.pBodyPart = new BodyPartElements();
		this.ePromptType = new PromptTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.disim.cacher.Cacher".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Prompt:
	//    ('This' 'is' name=ID '.')? &
	//    ('Use' usedPrompts=UsedPromptsList)? &
	//    ('Accepts' bodyParams=BodyParamsList 'as' 'parameters' '.')? &
	//    ('The' 'given' 'context' 'is' context=Context)? &
	//    ('My' 'problem' 'is' request=Request) &
	//    ('You' 'must' ':' posConst=ConstraintList)? &
	//    ('You' 'must' 'not' ':' negConst=ConstraintList)? &
	//    ('The' 'output' 'must' ':' dataPresent=OutputConstraintList)? &
	//    ('Generate' 'a' promptType=PromptType 'prompt' '.')?
	//;
	public PromptElements getPromptAccess() {
		return pPrompt;
	}
	
	public ParserRule getPromptRule() {
		return getPromptAccess().getRule();
	}
	
	//BodyParamsList:
	//    list+=BodyParam (',' list+=BodyParam)*
	//;
	public BodyParamsListElements getBodyParamsListAccess() {
		return pBodyParamsList;
	}
	
	public ParserRule getBodyParamsListRule() {
		return getBodyParamsListAccess().getRule();
	}
	
	//UsedPromptsList:
	//    list+=ExternalRef (',' list+=ExternalRef)* '.'
	//;
	public UsedPromptsListElements getUsedPromptsListAccess() {
		return pUsedPromptsList;
	}
	
	public ParserRule getUsedPromptsListRule() {
		return getUsedPromptsListAccess().getRule();
	}
	
	//Context:
	//    (external+=ExternalRef ('and' external+=ExternalRef)* | body=STRING) '.'
	//;
	public ContextElements getContextAccess() {
		return pContext;
	}
	
	public ParserRule getContextRule() {
		return getContextAccess().getRule();
	}
	
	//Request:
	//    body+=BodyPart (',' body+=BodyPart)* '.'
	//;
	public RequestElements getRequestAccess() {
		return pRequest;
	}
	
	public ParserRule getRequestRule() {
		return getRequestAccess().getRule();
	}
	
	//ConstraintList:
	//    list+=Constraint (';' list+=Constraint)* '.'
	//;
	public ConstraintListElements getConstraintListAccess() {
		return pConstraintList;
	}
	
	public ParserRule getConstraintListRule() {
		return getConstraintListAccess().getRule();
	}
	
	//Constraint:
	//    //body=STRING
	//    body+=BodyPart (',' body+=BodyPart)*
	//;
	public ConstraintElements getConstraintAccess() {
		return pConstraint;
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}
	
	//OutputConstraintList:
	//    list+=OutputConstraint (';' list+=OutputConstraint)* '.'
	//;
	public OutputConstraintListElements getOutputConstraintListAccess() {
		return pOutputConstraintList;
	}
	
	public ParserRule getOutputConstraintListRule() {
		return getOutputConstraintListAccess().getRule();
	}
	
	//OutputConstraint:
	//    //body=STRING
	//    body+=BodyPart (',' body+=BodyPart)*
	//;
	public OutputConstraintElements getOutputConstraintAccess() {
		return pOutputConstraint;
	}
	
	public ParserRule getOutputConstraintRule() {
		return getOutputConstraintAccess().getRule();
	}
	
	///* My external refs */
	//ExternalRefParam:
	//    pname=ID '=' pval=STRING
	//;
	public ExternalRefParamElements getExternalRefParamAccess() {
		return pExternalRefParam;
	}
	
	public ParserRule getExternalRefParamRule() {
		return getExternalRefParamAccess().getRule();
	}
	
	//ExternalRef:
	//    part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
	//;
	public ExternalRefElements getExternalRefAccess() {
		return pExternalRef;
	}
	
	public ParserRule getExternalRefRule() {
		return getExternalRefAccess().getRule();
	}
	
	///* My body parts */
	//BodyParam:
	//    name=ID ('=' def=STRING)?
	//;
	public BodyParamElements getBodyParamAccess() {
		return pBodyParam;
	}
	
	public ParserRule getBodyParamRule() {
		return getBodyParamAccess().getRule();
	}
	
	//BodyPart:
	//    content=STRING |
	//    param=[BodyParam]
	//;
	public BodyPartElements getBodyPartAccess() {
		return pBodyPart;
	}
	
	public ParserRule getBodyPartRule() {
		return getBodyPartAccess().getRule();
	}
	
	//enum PromptType:
	//    NL='natural language' | TAG='tag based'
	//;
	public PromptTypeElements getPromptTypeAccess() {
		return ePromptType;
	}
	
	public EnumRule getPromptTypeRule() {
		return getPromptTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
