/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractChainsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.disim.cacher.chains.chains.ChainsPackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.xtext.org/disim/cacher/Cacher"));
		return result;
	}
}
