/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CacherStandaloneSetup extends CacherStandaloneSetupGenerated {

	public static void doSetup() {
		new CacherStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
