/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.disim.cacher.cacher.CacherPackage;
import org.xtext.disim.cacher.cacher.ExternalRef;
import org.xtext.disim.cacher.cacher.ExternalRefParam;
import org.xtext.disim.cacher.chains.chains.Chain;
import org.xtext.disim.cacher.chains.chains.ChainsPackage;
import org.xtext.disim.cacher.chains.chains.PromptChain;
import org.xtext.disim.cacher.chains.services.ChainsGrammarAccess;

@SuppressWarnings("all")
public class ChainsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ChainsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CacherPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CacherPackage.EXTERNAL_REF:
				sequence_ExternalRef(context, (ExternalRef) semanticObject); 
				return; 
			case CacherPackage.EXTERNAL_REF_PARAM:
				sequence_ExternalRefParam(context, (ExternalRefParam) semanticObject); 
				return; 
			}
		else if (epackage == ChainsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ChainsPackage.CHAIN:
				sequence_Chain(context, (Chain) semanticObject); 
				return; 
			case ChainsPackage.PROMPT_CHAIN:
				sequence_PromptChain(context, (PromptChain) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Chain returns Chain
	 *
	 * Constraint:
	 *     (name=ID | (chain=PromptChain chainType=ChainType?))+
	 * </pre>
	 */
	protected void sequence_Chain(ISerializationContext context, Chain semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExternalRefParam returns ExternalRefParam
	 *
	 * Constraint:
	 *     (pname=ID pval=STRING)
	 * </pre>
	 */
	protected void sequence_ExternalRefParam(ISerializationContext context, ExternalRefParam semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PNAME));
			if (transientValues.isValueTransient(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PVAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CacherPackage.Literals.EXTERNAL_REF_PARAM__PVAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExternalRefParamAccess().getPnameIDTerminalRuleCall_0_0(), semanticObject.getPname());
		feeder.accept(grammarAccess.getExternalRefParamAccess().getPvalSTRINGTerminalRuleCall_2_0(), semanticObject.getPval());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExternalRef returns ExternalRef
	 *
	 * Constraint:
	 *     (part=[Prompt|ID] (params+=ExternalRefParam params+=ExternalRefParam*)?)
	 * </pre>
	 */
	protected void sequence_ExternalRef(ISerializationContext context, ExternalRef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PromptChain returns PromptChain
	 *
	 * Constraint:
	 *     (list+=ExternalRef list+=ExternalRef*)
	 * </pre>
	 */
	protected void sequence_PromptChain(ISerializationContext context, PromptChain semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
