/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ChainsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ChainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.chains.Chains.Chain");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cThisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cIsKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cFullStopKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Keyword cChainKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cTheseKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cPromptsKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final Keyword cColonKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Assignment cChainAssignment_1_0_4 = (Assignment)cGroup_1_0.eContents().get(4);
		private final RuleCall cChainPromptChainParserRuleCall_1_0_4_0 = (RuleCall)cChainAssignment_1_0_4.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cGenerateKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cAllKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Keyword cUsingKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Assignment cChainTypeAssignment_1_1_3 = (Assignment)cGroup_1_1.eContents().get(3);
		private final RuleCall cChainTypeChainTypeEnumRuleCall_1_1_3_0 = (RuleCall)cChainTypeAssignment_1_1_3.eContents().get(0);
		private final Keyword cPromptsKeyword_1_1_4 = (Keyword)cGroup_1_1.eContents().get(4);
		private final Keyword cFullStopKeyword_1_1_5 = (Keyword)cGroup_1_1.eContents().get(5);
		
		//Chain:
		//    ('This' 'is' name=ID '.')? &
		//    ('Chain' 'these' 'prompts' ':' chain=PromptChain)
		//    ('Generate' 'all' 'using' chainType=ChainType 'prompts' '.')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('This' 'is' name=ID '.')? &
		//('Chain' 'these' 'prompts' ':' chain=PromptChain)
		//('Generate' 'all' 'using' chainType=ChainType 'prompts' '.')?
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//('This' 'is' name=ID '.')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'This'
		public Keyword getThisKeyword_0_0() { return cThisKeyword_0_0; }
		
		//'is'
		public Keyword getIsKeyword_0_1() { return cIsKeyword_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }
		
		//'.'
		public Keyword getFullStopKeyword_0_3() { return cFullStopKeyword_0_3; }
		
		//('Chain' 'these' 'prompts' ':' chain=PromptChain)
		//('Generate' 'all' 'using' chainType=ChainType 'prompts' '.')?
		public Group getGroup_1() { return cGroup_1; }
		
		//('Chain' 'these' 'prompts' ':' chain=PromptChain)
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'Chain'
		public Keyword getChainKeyword_1_0_0() { return cChainKeyword_1_0_0; }
		
		//'these'
		public Keyword getTheseKeyword_1_0_1() { return cTheseKeyword_1_0_1; }
		
		//'prompts'
		public Keyword getPromptsKeyword_1_0_2() { return cPromptsKeyword_1_0_2; }
		
		//':'
		public Keyword getColonKeyword_1_0_3() { return cColonKeyword_1_0_3; }
		
		//chain=PromptChain
		public Assignment getChainAssignment_1_0_4() { return cChainAssignment_1_0_4; }
		
		//PromptChain
		public RuleCall getChainPromptChainParserRuleCall_1_0_4_0() { return cChainPromptChainParserRuleCall_1_0_4_0; }
		
		//('Generate' 'all' 'using' chainType=ChainType 'prompts' '.')?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'Generate'
		public Keyword getGenerateKeyword_1_1_0() { return cGenerateKeyword_1_1_0; }
		
		//'all'
		public Keyword getAllKeyword_1_1_1() { return cAllKeyword_1_1_1; }
		
		//'using'
		public Keyword getUsingKeyword_1_1_2() { return cUsingKeyword_1_1_2; }
		
		//chainType=ChainType
		public Assignment getChainTypeAssignment_1_1_3() { return cChainTypeAssignment_1_1_3; }
		
		//ChainType
		public RuleCall getChainTypeChainTypeEnumRuleCall_1_1_3_0() { return cChainTypeChainTypeEnumRuleCall_1_1_3_0; }
		
		//'prompts'
		public Keyword getPromptsKeyword_1_1_4() { return cPromptsKeyword_1_1_4; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1_5() { return cFullStopKeyword_1_1_5; }
	}
	public class PromptChainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.chains.Chains.PromptChain");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cListExternalRefParserRuleCall_0_0 = (RuleCall)cListAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cListAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cListExternalRefParserRuleCall_1_1_0 = (RuleCall)cListAssignment_1_1.eContents().get(0);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//PromptChain:
		//    list+=ExternalRef (',' list+=ExternalRef)* '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//list+=ExternalRef (',' list+=ExternalRef)* '.'
		public Group getGroup() { return cGroup; }
		
		//list+=ExternalRef
		public Assignment getListAssignment_0() { return cListAssignment_0; }
		
		//ExternalRef
		public RuleCall getListExternalRefParserRuleCall_0_0() { return cListExternalRefParserRuleCall_0_0; }
		
		//(',' list+=ExternalRef)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//list+=ExternalRef
		public Assignment getListAssignment_1_1() { return cListAssignment_1_1; }
		
		//ExternalRef
		public RuleCall getListExternalRefParserRuleCall_1_1_0() { return cListExternalRefParserRuleCall_1_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}
	public class ExternalRefParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.chains.Chains.ExternalRefParam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPnameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPnameIDTerminalRuleCall_0_0 = (RuleCall)cPnameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPvalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPvalSTRINGTerminalRuleCall_2_0 = (RuleCall)cPvalAssignment_2.eContents().get(0);
		
		///* My external refs */
		//ExternalRefParam:
		//    pname=ID '=' pval=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//pname=ID '=' pval=STRING
		public Group getGroup() { return cGroup; }
		
		//pname=ID
		public Assignment getPnameAssignment_0() { return cPnameAssignment_0; }
		
		//ID
		public RuleCall getPnameIDTerminalRuleCall_0_0() { return cPnameIDTerminalRuleCall_0_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//pval=STRING
		public Assignment getPvalAssignment_2() { return cPvalAssignment_2; }
		
		//STRING
		public RuleCall getPvalSTRINGTerminalRuleCall_2_0() { return cPvalSTRINGTerminalRuleCall_2_0; }
	}
	public class ExternalRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.chains.Chains.ExternalRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPartAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPartPromptCrossReference_0_0 = (CrossReference)cPartAssignment_0.eContents().get(0);
		private final RuleCall cPartPromptIDTerminalRuleCall_0_0_1 = (RuleCall)cPartPromptCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cParamsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cParamsExternalRefParamParserRuleCall_1_1_0 = (RuleCall)cParamsAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cParamsAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cParamsExternalRefParamParserRuleCall_1_2_1_0 = (RuleCall)cParamsAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//ExternalRef:
		//    part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		public Group getGroup() { return cGroup; }
		
		//part=[Prompt]
		public Assignment getPartAssignment_0() { return cPartAssignment_0; }
		
		//[Prompt]
		public CrossReference getPartPromptCrossReference_0_0() { return cPartPromptCrossReference_0_0; }
		
		//ID
		public RuleCall getPartPromptIDTerminalRuleCall_0_0_1() { return cPartPromptIDTerminalRuleCall_0_0_1; }
		
		//('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//params+=ExternalRefParam
		public Assignment getParamsAssignment_1_1() { return cParamsAssignment_1_1; }
		
		//ExternalRefParam
		public RuleCall getParamsExternalRefParamParserRuleCall_1_1_0() { return cParamsExternalRefParamParserRuleCall_1_1_0; }
		
		//(',' params+=ExternalRefParam)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//params+=ExternalRefParam
		public Assignment getParamsAssignment_1_2_1() { return cParamsAssignment_1_2_1; }
		
		//ExternalRefParam
		public RuleCall getParamsExternalRefParamParserRuleCall_1_2_1_0() { return cParamsExternalRefParamParserRuleCall_1_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	
	public class ChainTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.disim.cacher.chains.Chains.ChainType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNONENoneKeyword_0_0 = (Keyword)cNONEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNLEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNLNaturalLanguageKeyword_1_0 = (Keyword)cNLEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTAGEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTAGTagBasedKeyword_2_0 = (Keyword)cTAGEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ChainType:
		//    NONE='none' | NL='natural language' | TAG='tag based'
		//;
		public EnumRule getRule() { return rule; }
		
		//NONE='none' | NL='natural language' | TAG='tag based'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NONE='none'
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_0() { return cNONEEnumLiteralDeclaration_0; }
		
		//'none'
		public Keyword getNONENoneKeyword_0_0() { return cNONENoneKeyword_0_0; }
		
		//NL='natural language'
		public EnumLiteralDeclaration getNLEnumLiteralDeclaration_1() { return cNLEnumLiteralDeclaration_1; }
		
		//'natural language'
		public Keyword getNLNaturalLanguageKeyword_1_0() { return cNLNaturalLanguageKeyword_1_0; }
		
		//TAG='tag based'
		public EnumLiteralDeclaration getTAGEnumLiteralDeclaration_2() { return cTAGEnumLiteralDeclaration_2; }
		
		//'tag based'
		public Keyword getTAGTagBasedKeyword_2_0() { return cTAGTagBasedKeyword_2_0; }
	}
	
	private final ChainElements pChain;
	private final PromptChainElements pPromptChain;
	private final ExternalRefParamElements pExternalRefParam;
	private final ExternalRefElements pExternalRef;
	private final ChainTypeElements eChainType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ChainsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pChain = new ChainElements();
		this.pPromptChain = new PromptChainElements();
		this.pExternalRefParam = new ExternalRefParamElements();
		this.pExternalRef = new ExternalRefElements();
		this.eChainType = new ChainTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.disim.cacher.chains.Chains".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Chain:
	//    ('This' 'is' name=ID '.')? &
	//    ('Chain' 'these' 'prompts' ':' chain=PromptChain)
	//    ('Generate' 'all' 'using' chainType=ChainType 'prompts' '.')?
	//;
	public ChainElements getChainAccess() {
		return pChain;
	}
	
	public ParserRule getChainRule() {
		return getChainAccess().getRule();
	}
	
	//PromptChain:
	//    list+=ExternalRef (',' list+=ExternalRef)* '.'
	//;
	public PromptChainElements getPromptChainAccess() {
		return pPromptChain;
	}
	
	public ParserRule getPromptChainRule() {
		return getPromptChainAccess().getRule();
	}
	
	///* My external refs */
	//ExternalRefParam:
	//    pname=ID '=' pval=STRING
	//;
	public ExternalRefParamElements getExternalRefParamAccess() {
		return pExternalRefParam;
	}
	
	public ParserRule getExternalRefParamRule() {
		return getExternalRefParamAccess().getRule();
	}
	
	//ExternalRef:
	//    part=[Prompt] ('(' params+=ExternalRefParam (',' params+=ExternalRefParam)* ')')?
	//;
	public ExternalRefElements getExternalRefAccess() {
		return pExternalRef;
	}
	
	public ParserRule getExternalRefRule() {
		return getExternalRefAccess().getRule();
	}
	
	//enum ChainType:
	//    NONE='none' | NL='natural language' | TAG='tag based'
	//;
	public ChainTypeElements getChainTypeAccess() {
		return eChainType;
	}
	
	public EnumRule getChainTypeRule() {
		return getChainTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
