/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.disim.cacher.chains.ui.internal.ChainsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChainsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ChainsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ChainsActivator activator = ChainsActivator.getInstance();
		return activator != null ? activator.getInjector(ChainsActivator.ORG_XTEXT_DISIM_CACHER_CHAINS_CHAINS) : null;
	}

}
