/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractChainsScopeProvider extends DelegatingScopeProvider {
}
