/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.disim.cacher.ui.internal.CacherActivator;

public class CacherUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CacherActivator.getInstance().getInjector("org.xtext.disim.cacher.Cacher");
	}

}
