/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.disim.cacher.ide.contentassist.antlr.internal.InternalCacherParser;
import org.xtext.disim.cacher.services.CacherGrammarAccess;

public class CacherParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CacherGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CacherGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getContextAccess().getAlternatives_0(), "rule__Context__Alternatives_0");
			builder.put(grammarAccess.getBodyPartAccess().getAlternatives(), "rule__BodyPart__Alternatives");
			builder.put(grammarAccess.getPromptTypeAccess().getAlternatives(), "rule__PromptType__Alternatives");
			builder.put(grammarAccess.getPromptAccess().getGroup_0(), "rule__Prompt__Group_0__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_1(), "rule__Prompt__Group_1__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_2(), "rule__Prompt__Group_2__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_3(), "rule__Prompt__Group_3__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_4(), "rule__Prompt__Group_4__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_5(), "rule__Prompt__Group_5__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_6(), "rule__Prompt__Group_6__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_7(), "rule__Prompt__Group_7__0");
			builder.put(grammarAccess.getPromptAccess().getGroup_8(), "rule__Prompt__Group_8__0");
			builder.put(grammarAccess.getBodyParamsListAccess().getGroup(), "rule__BodyParamsList__Group__0");
			builder.put(grammarAccess.getBodyParamsListAccess().getGroup_1(), "rule__BodyParamsList__Group_1__0");
			builder.put(grammarAccess.getUsedPromptsListAccess().getGroup(), "rule__UsedPromptsList__Group__0");
			builder.put(grammarAccess.getUsedPromptsListAccess().getGroup_1(), "rule__UsedPromptsList__Group_1__0");
			builder.put(grammarAccess.getContextAccess().getGroup(), "rule__Context__Group__0");
			builder.put(grammarAccess.getContextAccess().getGroup_0_0(), "rule__Context__Group_0_0__0");
			builder.put(grammarAccess.getContextAccess().getGroup_0_0_1(), "rule__Context__Group_0_0_1__0");
			builder.put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
			builder.put(grammarAccess.getRequestAccess().getGroup_1(), "rule__Request__Group_1__0");
			builder.put(grammarAccess.getConstraintListAccess().getGroup(), "rule__ConstraintList__Group__0");
			builder.put(grammarAccess.getConstraintListAccess().getGroup_1(), "rule__ConstraintList__Group_1__0");
			builder.put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
			builder.put(grammarAccess.getConstraintAccess().getGroup_1(), "rule__Constraint__Group_1__0");
			builder.put(grammarAccess.getOutputConstraintListAccess().getGroup(), "rule__OutputConstraintList__Group__0");
			builder.put(grammarAccess.getOutputConstraintListAccess().getGroup_1(), "rule__OutputConstraintList__Group_1__0");
			builder.put(grammarAccess.getOutputConstraintAccess().getGroup(), "rule__OutputConstraint__Group__0");
			builder.put(grammarAccess.getOutputConstraintAccess().getGroup_1(), "rule__OutputConstraint__Group_1__0");
			builder.put(grammarAccess.getExternalRefParamAccess().getGroup(), "rule__ExternalRefParam__Group__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup(), "rule__ExternalRef__Group__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup_1(), "rule__ExternalRef__Group_1__0");
			builder.put(grammarAccess.getExternalRefAccess().getGroup_1_2(), "rule__ExternalRef__Group_1_2__0");
			builder.put(grammarAccess.getBodyParamAccess().getGroup(), "rule__BodyParam__Group__0");
			builder.put(grammarAccess.getBodyParamAccess().getGroup_1(), "rule__BodyParam__Group_1__0");
			builder.put(grammarAccess.getPromptAccess().getNameAssignment_0_2(), "rule__Prompt__NameAssignment_0_2");
			builder.put(grammarAccess.getPromptAccess().getUsedPromptsAssignment_1_1(), "rule__Prompt__UsedPromptsAssignment_1_1");
			builder.put(grammarAccess.getPromptAccess().getBodyParamsAssignment_2_1(), "rule__Prompt__BodyParamsAssignment_2_1");
			builder.put(grammarAccess.getPromptAccess().getContextAssignment_3_4(), "rule__Prompt__ContextAssignment_3_4");
			builder.put(grammarAccess.getPromptAccess().getRequestAssignment_4_3(), "rule__Prompt__RequestAssignment_4_3");
			builder.put(grammarAccess.getPromptAccess().getPosConstAssignment_5_3(), "rule__Prompt__PosConstAssignment_5_3");
			builder.put(grammarAccess.getPromptAccess().getNegConstAssignment_6_4(), "rule__Prompt__NegConstAssignment_6_4");
			builder.put(grammarAccess.getPromptAccess().getDataPresentAssignment_7_4(), "rule__Prompt__DataPresentAssignment_7_4");
			builder.put(grammarAccess.getPromptAccess().getPromptTypeAssignment_8_2(), "rule__Prompt__PromptTypeAssignment_8_2");
			builder.put(grammarAccess.getBodyParamsListAccess().getListAssignment_0(), "rule__BodyParamsList__ListAssignment_0");
			builder.put(grammarAccess.getBodyParamsListAccess().getListAssignment_1_1(), "rule__BodyParamsList__ListAssignment_1_1");
			builder.put(grammarAccess.getUsedPromptsListAccess().getListAssignment_0(), "rule__UsedPromptsList__ListAssignment_0");
			builder.put(grammarAccess.getUsedPromptsListAccess().getListAssignment_1_1(), "rule__UsedPromptsList__ListAssignment_1_1");
			builder.put(grammarAccess.getContextAccess().getExternalAssignment_0_0_0(), "rule__Context__ExternalAssignment_0_0_0");
			builder.put(grammarAccess.getContextAccess().getExternalAssignment_0_0_1_1(), "rule__Context__ExternalAssignment_0_0_1_1");
			builder.put(grammarAccess.getContextAccess().getBodyAssignment_0_1(), "rule__Context__BodyAssignment_0_1");
			builder.put(grammarAccess.getRequestAccess().getBodyAssignment_0(), "rule__Request__BodyAssignment_0");
			builder.put(grammarAccess.getRequestAccess().getBodyAssignment_1_1(), "rule__Request__BodyAssignment_1_1");
			builder.put(grammarAccess.getConstraintListAccess().getListAssignment_0(), "rule__ConstraintList__ListAssignment_0");
			builder.put(grammarAccess.getConstraintListAccess().getListAssignment_1_1(), "rule__ConstraintList__ListAssignment_1_1");
			builder.put(grammarAccess.getConstraintAccess().getBodyAssignment_0(), "rule__Constraint__BodyAssignment_0");
			builder.put(grammarAccess.getConstraintAccess().getBodyAssignment_1_1(), "rule__Constraint__BodyAssignment_1_1");
			builder.put(grammarAccess.getOutputConstraintListAccess().getListAssignment_0(), "rule__OutputConstraintList__ListAssignment_0");
			builder.put(grammarAccess.getOutputConstraintListAccess().getListAssignment_1_1(), "rule__OutputConstraintList__ListAssignment_1_1");
			builder.put(grammarAccess.getOutputConstraintAccess().getBodyAssignment_0(), "rule__OutputConstraint__BodyAssignment_0");
			builder.put(grammarAccess.getOutputConstraintAccess().getBodyAssignment_1_1(), "rule__OutputConstraint__BodyAssignment_1_1");
			builder.put(grammarAccess.getExternalRefParamAccess().getPnameAssignment_0(), "rule__ExternalRefParam__PnameAssignment_0");
			builder.put(grammarAccess.getExternalRefParamAccess().getPvalAssignment_2(), "rule__ExternalRefParam__PvalAssignment_2");
			builder.put(grammarAccess.getExternalRefAccess().getPartAssignment_0(), "rule__ExternalRef__PartAssignment_0");
			builder.put(grammarAccess.getExternalRefAccess().getParamsAssignment_1_1(), "rule__ExternalRef__ParamsAssignment_1_1");
			builder.put(grammarAccess.getExternalRefAccess().getParamsAssignment_1_2_1(), "rule__ExternalRef__ParamsAssignment_1_2_1");
			builder.put(grammarAccess.getBodyParamAccess().getNameAssignment_0(), "rule__BodyParam__NameAssignment_0");
			builder.put(grammarAccess.getBodyParamAccess().getDefAssignment_1_1(), "rule__BodyParam__DefAssignment_1_1");
			builder.put(grammarAccess.getBodyPartAccess().getContentAssignment_0(), "rule__BodyPart__ContentAssignment_0");
			builder.put(grammarAccess.getBodyPartAccess().getParamAssignment_1(), "rule__BodyPart__ParamAssignment_1");
			builder.put(grammarAccess.getPromptAccess().getUnorderedGroup(), "rule__Prompt__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CacherGrammarAccess grammarAccess;

	@Override
	protected InternalCacherParser createParser() {
		InternalCacherParser result = new InternalCacherParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CacherGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CacherGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
