/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.disim.cacher.chains.chains.ChainsPackage
 * @generated
 */
public interface ChainsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ChainsFactory eINSTANCE = org.xtext.disim.cacher.chains.chains.impl.ChainsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chain</em>'.
   * @generated
   */
  Chain createChain();

  /**
   * Returns a new object of class '<em>Prompt Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prompt Chain</em>'.
   * @generated
   */
  PromptChain createPromptChain();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ChainsPackage getChainsPackage();

} //ChainsFactory
