/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.Chain#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.Chain#getChain <em>Chain</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.Chain#getChainType <em>Chain Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getChain()
 * @model
 * @generated
 */
public interface Chain extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getChain_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.chains.chains.Chain#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chain</em>' containment reference.
   * @see #setChain(PromptChain)
   * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getChain_Chain()
   * @model containment="true"
   * @generated
   */
  PromptChain getChain();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.chains.chains.Chain#getChain <em>Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chain</em>' containment reference.
   * @see #getChain()
   * @generated
   */
  void setChain(PromptChain value);

  /**
   * Returns the value of the '<em><b>Chain Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.disim.cacher.chains.chains.ChainType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chain Type</em>' attribute.
   * @see org.xtext.disim.cacher.chains.chains.ChainType
   * @see #setChainType(ChainType)
   * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getChain_ChainType()
   * @model
   * @generated
   */
  ChainType getChainType();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.chains.chains.Chain#getChainType <em>Chain Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chain Type</em>' attribute.
   * @see org.xtext.disim.cacher.chains.chains.ChainType
   * @see #getChainType()
   * @generated
   */
  void setChainType(ChainType value);

} // Chain
