/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.disim.cacher.chains.chains.ChainsFactory
 * @model kind="package"
 * @generated
 */
public interface ChainsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "chains";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/disim/cacher/chains/Chains";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "chains";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ChainsPackage eINSTANCE = org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.chains.chains.impl.ChainImpl <em>Chain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.chains.chains.impl.ChainImpl
   * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getChain()
   * @generated
   */
  int CHAIN = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__CHAIN = 1;

  /**
   * The feature id for the '<em><b>Chain Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN__CHAIN_TYPE = 2;

  /**
   * The number of structural features of the '<em>Chain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.chains.chains.impl.PromptChainImpl <em>Prompt Chain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.chains.chains.impl.PromptChainImpl
   * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getPromptChain()
   * @generated
   */
  int PROMPT_CHAIN = 1;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT_CHAIN__LIST = 0;

  /**
   * The number of structural features of the '<em>Prompt Chain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT_CHAIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.chains.chains.ChainType <em>Chain Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.chains.chains.ChainType
   * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getChainType()
   * @generated
   */
  int CHAIN_TYPE = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.chains.chains.Chain <em>Chain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chain</em>'.
   * @see org.xtext.disim.cacher.chains.chains.Chain
   * @generated
   */
  EClass getChain();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.chains.chains.Chain#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.disim.cacher.chains.chains.Chain#getName()
   * @see #getChain()
   * @generated
   */
  EAttribute getChain_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.chains.chains.Chain#getChain <em>Chain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Chain</em>'.
   * @see org.xtext.disim.cacher.chains.chains.Chain#getChain()
   * @see #getChain()
   * @generated
   */
  EReference getChain_Chain();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.chains.chains.Chain#getChainType <em>Chain Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chain Type</em>'.
   * @see org.xtext.disim.cacher.chains.chains.Chain#getChainType()
   * @see #getChain()
   * @generated
   */
  EAttribute getChain_ChainType();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.chains.chains.PromptChain <em>Prompt Chain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prompt Chain</em>'.
   * @see org.xtext.disim.cacher.chains.chains.PromptChain
   * @generated
   */
  EClass getPromptChain();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.chains.chains.PromptChain#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.xtext.disim.cacher.chains.chains.PromptChain#getList()
   * @see #getPromptChain()
   * @generated
   */
  EReference getPromptChain_List();

  /**
   * Returns the meta object for enum '{@link org.xtext.disim.cacher.chains.chains.ChainType <em>Chain Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Chain Type</em>'.
   * @see org.xtext.disim.cacher.chains.chains.ChainType
   * @generated
   */
  EEnum getChainType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ChainsFactory getChainsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.chains.chains.impl.ChainImpl <em>Chain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.chains.chains.impl.ChainImpl
     * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getChain()
     * @generated
     */
    EClass CHAIN = eINSTANCE.getChain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN__NAME = eINSTANCE.getChain_Name();

    /**
     * The meta object literal for the '<em><b>Chain</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAIN__CHAIN = eINSTANCE.getChain_Chain();

    /**
     * The meta object literal for the '<em><b>Chain Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAIN__CHAIN_TYPE = eINSTANCE.getChain_ChainType();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.chains.chains.impl.PromptChainImpl <em>Prompt Chain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.chains.chains.impl.PromptChainImpl
     * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getPromptChain()
     * @generated
     */
    EClass PROMPT_CHAIN = eINSTANCE.getPromptChain();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT_CHAIN__LIST = eINSTANCE.getPromptChain_List();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.chains.chains.ChainType <em>Chain Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.chains.chains.ChainType
     * @see org.xtext.disim.cacher.chains.chains.impl.ChainsPackageImpl#getChainType()
     * @generated
     */
    EEnum CHAIN_TYPE = eINSTANCE.getChainType();

  }

} //ChainsPackage
