/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.chains.chains;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.xtext.disim.cacher.cacher.ExternalRef;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prompt Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.chains.chains.PromptChain#getList <em>List</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getPromptChain()
 * @model
 * @generated
 */
public interface PromptChain extends EObject
{
  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.disim.cacher.cacher.ExternalRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference list.
   * @see org.xtext.disim.cacher.chains.chains.ChainsPackage#getPromptChain_List()
   * @model containment="true"
   * @generated
   */
  EList<ExternalRef> getList();

} // PromptChain
