/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.BodyPart#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.BodyPart#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getBodyPart()
 * @model
 * @generated
 */
public interface BodyPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getBodyPart_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.BodyPart#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' reference.
   * @see #setParam(BodyParam)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getBodyPart_Param()
   * @model
   * @generated
   */
  BodyParam getParam();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.BodyPart#getParam <em>Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' reference.
   * @see #getParam()
   * @generated
   */
  void setParam(BodyParam value);

} // BodyPart
