/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.disim.cacher.cacher.CacherFactory
 * @model kind="package"
 * @generated
 */
public interface CacherPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cacher";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/disim/cacher/Cacher";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cacher";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CacherPackage eINSTANCE = org.xtext.disim.cacher.cacher.impl.CacherPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.PromptImpl <em>Prompt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.PromptImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getPrompt()
   * @generated
   */
  int PROMPT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Used Prompts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__USED_PROMPTS = 1;

  /**
   * The feature id for the '<em><b>Body Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__BODY_PARAMS = 2;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__CONTEXT = 3;

  /**
   * The feature id for the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__REQUEST = 4;

  /**
   * The feature id for the '<em><b>Pos Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__POS_CONST = 5;

  /**
   * The feature id for the '<em><b>Neg Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__NEG_CONST = 6;

  /**
   * The feature id for the '<em><b>Data Present</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__DATA_PRESENT = 7;

  /**
   * The feature id for the '<em><b>Prompt Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__PROMPT_TYPE = 8;

  /**
   * The number of structural features of the '<em>Prompt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.BodyParamsListImpl <em>Body Params List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.BodyParamsListImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyParamsList()
   * @generated
   */
  int BODY_PARAMS_LIST = 1;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PARAMS_LIST__LIST = 0;

  /**
   * The number of structural features of the '<em>Body Params List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PARAMS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.UsedPromptsListImpl <em>Used Prompts List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.UsedPromptsListImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getUsedPromptsList()
   * @generated
   */
  int USED_PROMPTS_LIST = 2;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USED_PROMPTS_LIST__LIST = 0;

  /**
   * The number of structural features of the '<em>Used Prompts List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USED_PROMPTS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.ContextImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 3;

  /**
   * The feature id for the '<em><b>External</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__EXTERNAL = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__BODY = 1;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.RequestImpl <em>Request</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.RequestImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getRequest()
   * @generated
   */
  int REQUEST = 4;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUEST__BODY = 0;

  /**
   * The number of structural features of the '<em>Request</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUEST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.ConstraintListImpl <em>Constraint List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.ConstraintListImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getConstraintList()
   * @generated
   */
  int CONSTRAINT_LIST = 5;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_LIST__LIST = 0;

  /**
   * The number of structural features of the '<em>Constraint List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.ConstraintImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 6;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__BODY = 0;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.OutputConstraintListImpl <em>Output Constraint List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.OutputConstraintListImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getOutputConstraintList()
   * @generated
   */
  int OUTPUT_CONSTRAINT_LIST = 7;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_CONSTRAINT_LIST__LIST = 0;

  /**
   * The number of structural features of the '<em>Output Constraint List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_CONSTRAINT_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.OutputConstraintImpl <em>Output Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.OutputConstraintImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getOutputConstraint()
   * @generated
   */
  int OUTPUT_CONSTRAINT = 8;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_CONSTRAINT__BODY = 0;

  /**
   * The number of structural features of the '<em>Output Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl <em>External Ref Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getExternalRefParam()
   * @generated
   */
  int EXTERNAL_REF_PARAM = 9;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF_PARAM__PNAME = 0;

  /**
   * The feature id for the '<em><b>Pval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF_PARAM__PVAL = 1;

  /**
   * The number of structural features of the '<em>External Ref Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.ExternalRefImpl <em>External Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.ExternalRefImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getExternalRef()
   * @generated
   */
  int EXTERNAL_REF = 10;

  /**
   * The feature id for the '<em><b>Part</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF__PART = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF__PARAMS = 1;

  /**
   * The number of structural features of the '<em>External Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_REF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.BodyParamImpl <em>Body Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.BodyParamImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyParam()
   * @generated
   */
  int BODY_PARAM = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PARAM__DEF = 1;

  /**
   * The number of structural features of the '<em>Body Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.impl.BodyPartImpl <em>Body Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.impl.BodyPartImpl
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyPart()
   * @generated
   */
  int BODY_PART = 12;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PART__CONTENT = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PART__PARAM = 1;

  /**
   * The number of structural features of the '<em>Body Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_PART_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.disim.cacher.cacher.PromptType <em>Prompt Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.disim.cacher.cacher.PromptType
   * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getPromptType()
   * @generated
   */
  int PROMPT_TYPE = 13;


  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.Prompt <em>Prompt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prompt</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt
   * @generated
   */
  EClass getPrompt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.Prompt#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getName()
   * @see #getPrompt()
   * @generated
   */
  EAttribute getPrompt_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getUsedPrompts <em>Used Prompts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Used Prompts</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getUsedPrompts()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_UsedPrompts();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getBodyParams <em>Body Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body Params</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getBodyParams()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_BodyParams();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Context</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getContext()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_Context();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getRequest <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Request</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getRequest()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_Request();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getPosConst <em>Pos Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pos Const</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getPosConst()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_PosConst();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getNegConst <em>Neg Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Neg Const</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getNegConst()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_NegConst();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.disim.cacher.cacher.Prompt#getDataPresent <em>Data Present</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Data Present</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getDataPresent()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_DataPresent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.Prompt#getPromptType <em>Prompt Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prompt Type</em>'.
   * @see org.xtext.disim.cacher.cacher.Prompt#getPromptType()
   * @see #getPrompt()
   * @generated
   */
  EAttribute getPrompt_PromptType();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.BodyParamsList <em>Body Params List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body Params List</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyParamsList
   * @generated
   */
  EClass getBodyParamsList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.BodyParamsList#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyParamsList#getList()
   * @see #getBodyParamsList()
   * @generated
   */
  EReference getBodyParamsList_List();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.UsedPromptsList <em>Used Prompts List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Used Prompts List</em>'.
   * @see org.xtext.disim.cacher.cacher.UsedPromptsList
   * @generated
   */
  EClass getUsedPromptsList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.UsedPromptsList#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.xtext.disim.cacher.cacher.UsedPromptsList#getList()
   * @see #getUsedPromptsList()
   * @generated
   */
  EReference getUsedPromptsList_List();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see org.xtext.disim.cacher.cacher.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.Context#getExternal <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>External</em>'.
   * @see org.xtext.disim.cacher.cacher.Context#getExternal()
   * @see #getContext()
   * @generated
   */
  EReference getContext_External();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.Context#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Body</em>'.
   * @see org.xtext.disim.cacher.cacher.Context#getBody()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.Request <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Request</em>'.
   * @see org.xtext.disim.cacher.cacher.Request
   * @generated
   */
  EClass getRequest();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.Request#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.disim.cacher.cacher.Request#getBody()
   * @see #getRequest()
   * @generated
   */
  EReference getRequest_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.ConstraintList <em>Constraint List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint List</em>'.
   * @see org.xtext.disim.cacher.cacher.ConstraintList
   * @generated
   */
  EClass getConstraintList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.ConstraintList#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.xtext.disim.cacher.cacher.ConstraintList#getList()
   * @see #getConstraintList()
   * @generated
   */
  EReference getConstraintList_List();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.xtext.disim.cacher.cacher.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.Constraint#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.disim.cacher.cacher.Constraint#getBody()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.OutputConstraintList <em>Output Constraint List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output Constraint List</em>'.
   * @see org.xtext.disim.cacher.cacher.OutputConstraintList
   * @generated
   */
  EClass getOutputConstraintList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.OutputConstraintList#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.xtext.disim.cacher.cacher.OutputConstraintList#getList()
   * @see #getOutputConstraintList()
   * @generated
   */
  EReference getOutputConstraintList_List();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.OutputConstraint <em>Output Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output Constraint</em>'.
   * @see org.xtext.disim.cacher.cacher.OutputConstraint
   * @generated
   */
  EClass getOutputConstraint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.OutputConstraint#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.disim.cacher.cacher.OutputConstraint#getBody()
   * @see #getOutputConstraint()
   * @generated
   */
  EReference getOutputConstraint_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.ExternalRefParam <em>External Ref Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External Ref Param</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRefParam
   * @generated
   */
  EClass getExternalRefParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPname <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pname</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRefParam#getPname()
   * @see #getExternalRefParam()
   * @generated
   */
  EAttribute getExternalRefParam_Pname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPval <em>Pval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pval</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRefParam#getPval()
   * @see #getExternalRefParam()
   * @generated
   */
  EAttribute getExternalRefParam_Pval();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.ExternalRef <em>External Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External Ref</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRef
   * @generated
   */
  EClass getExternalRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.disim.cacher.cacher.ExternalRef#getPart <em>Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Part</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRef#getPart()
   * @see #getExternalRef()
   * @generated
   */
  EReference getExternalRef_Part();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.disim.cacher.cacher.ExternalRef#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.disim.cacher.cacher.ExternalRef#getParams()
   * @see #getExternalRef()
   * @generated
   */
  EReference getExternalRef_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.BodyParam <em>Body Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body Param</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyParam
   * @generated
   */
  EClass getBodyParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.BodyParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyParam#getName()
   * @see #getBodyParam()
   * @generated
   */
  EAttribute getBodyParam_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.BodyParam#getDef <em>Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Def</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyParam#getDef()
   * @see #getBodyParam()
   * @generated
   */
  EAttribute getBodyParam_Def();

  /**
   * Returns the meta object for class '{@link org.xtext.disim.cacher.cacher.BodyPart <em>Body Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body Part</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyPart
   * @generated
   */
  EClass getBodyPart();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.disim.cacher.cacher.BodyPart#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyPart#getContent()
   * @see #getBodyPart()
   * @generated
   */
  EAttribute getBodyPart_Content();

  /**
   * Returns the meta object for the reference '{@link org.xtext.disim.cacher.cacher.BodyPart#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see org.xtext.disim.cacher.cacher.BodyPart#getParam()
   * @see #getBodyPart()
   * @generated
   */
  EReference getBodyPart_Param();

  /**
   * Returns the meta object for enum '{@link org.xtext.disim.cacher.cacher.PromptType <em>Prompt Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Prompt Type</em>'.
   * @see org.xtext.disim.cacher.cacher.PromptType
   * @generated
   */
  EEnum getPromptType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CacherFactory getCacherFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.PromptImpl <em>Prompt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.PromptImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getPrompt()
     * @generated
     */
    EClass PROMPT = eINSTANCE.getPrompt();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROMPT__NAME = eINSTANCE.getPrompt_Name();

    /**
     * The meta object literal for the '<em><b>Used Prompts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__USED_PROMPTS = eINSTANCE.getPrompt_UsedPrompts();

    /**
     * The meta object literal for the '<em><b>Body Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__BODY_PARAMS = eINSTANCE.getPrompt_BodyParams();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__CONTEXT = eINSTANCE.getPrompt_Context();

    /**
     * The meta object literal for the '<em><b>Request</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__REQUEST = eINSTANCE.getPrompt_Request();

    /**
     * The meta object literal for the '<em><b>Pos Const</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__POS_CONST = eINSTANCE.getPrompt_PosConst();

    /**
     * The meta object literal for the '<em><b>Neg Const</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__NEG_CONST = eINSTANCE.getPrompt_NegConst();

    /**
     * The meta object literal for the '<em><b>Data Present</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__DATA_PRESENT = eINSTANCE.getPrompt_DataPresent();

    /**
     * The meta object literal for the '<em><b>Prompt Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROMPT__PROMPT_TYPE = eINSTANCE.getPrompt_PromptType();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.BodyParamsListImpl <em>Body Params List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.BodyParamsListImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyParamsList()
     * @generated
     */
    EClass BODY_PARAMS_LIST = eINSTANCE.getBodyParamsList();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY_PARAMS_LIST__LIST = eINSTANCE.getBodyParamsList_List();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.UsedPromptsListImpl <em>Used Prompts List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.UsedPromptsListImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getUsedPromptsList()
     * @generated
     */
    EClass USED_PROMPTS_LIST = eINSTANCE.getUsedPromptsList();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USED_PROMPTS_LIST__LIST = eINSTANCE.getUsedPromptsList_List();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.ContextImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>External</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__EXTERNAL = eINSTANCE.getContext_External();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__BODY = eINSTANCE.getContext_Body();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.RequestImpl <em>Request</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.RequestImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getRequest()
     * @generated
     */
    EClass REQUEST = eINSTANCE.getRequest();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUEST__BODY = eINSTANCE.getRequest_Body();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.ConstraintListImpl <em>Constraint List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.ConstraintListImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getConstraintList()
     * @generated
     */
    EClass CONSTRAINT_LIST = eINSTANCE.getConstraintList();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT_LIST__LIST = eINSTANCE.getConstraintList_List();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.ConstraintImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__BODY = eINSTANCE.getConstraint_Body();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.OutputConstraintListImpl <em>Output Constraint List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.OutputConstraintListImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getOutputConstraintList()
     * @generated
     */
    EClass OUTPUT_CONSTRAINT_LIST = eINSTANCE.getOutputConstraintList();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUT_CONSTRAINT_LIST__LIST = eINSTANCE.getOutputConstraintList_List();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.OutputConstraintImpl <em>Output Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.OutputConstraintImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getOutputConstraint()
     * @generated
     */
    EClass OUTPUT_CONSTRAINT = eINSTANCE.getOutputConstraint();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUT_CONSTRAINT__BODY = eINSTANCE.getOutputConstraint_Body();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl <em>External Ref Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.ExternalRefParamImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getExternalRefParam()
     * @generated
     */
    EClass EXTERNAL_REF_PARAM = eINSTANCE.getExternalRefParam();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL_REF_PARAM__PNAME = eINSTANCE.getExternalRefParam_Pname();

    /**
     * The meta object literal for the '<em><b>Pval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL_REF_PARAM__PVAL = eINSTANCE.getExternalRefParam_Pval();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.ExternalRefImpl <em>External Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.ExternalRefImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getExternalRef()
     * @generated
     */
    EClass EXTERNAL_REF = eINSTANCE.getExternalRef();

    /**
     * The meta object literal for the '<em><b>Part</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTERNAL_REF__PART = eINSTANCE.getExternalRef_Part();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTERNAL_REF__PARAMS = eINSTANCE.getExternalRef_Params();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.BodyParamImpl <em>Body Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.BodyParamImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyParam()
     * @generated
     */
    EClass BODY_PARAM = eINSTANCE.getBodyParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BODY_PARAM__NAME = eINSTANCE.getBodyParam_Name();

    /**
     * The meta object literal for the '<em><b>Def</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BODY_PARAM__DEF = eINSTANCE.getBodyParam_Def();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.impl.BodyPartImpl <em>Body Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.impl.BodyPartImpl
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getBodyPart()
     * @generated
     */
    EClass BODY_PART = eINSTANCE.getBodyPart();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BODY_PART__CONTENT = eINSTANCE.getBodyPart_Content();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY_PART__PARAM = eINSTANCE.getBodyPart_Param();

    /**
     * The meta object literal for the '{@link org.xtext.disim.cacher.cacher.PromptType <em>Prompt Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.disim.cacher.cacher.PromptType
     * @see org.xtext.disim.cacher.cacher.impl.CacherPackageImpl#getPromptType()
     * @generated
     */
    EEnum PROMPT_TYPE = eINSTANCE.getPromptType();

  }

} //CacherPackage
