/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.disim.cacher.cacher.CacherPackage
 * @generated
 */
public interface CacherFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CacherFactory eINSTANCE = org.xtext.disim.cacher.cacher.impl.CacherFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Prompt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prompt</em>'.
   * @generated
   */
  Prompt createPrompt();

  /**
   * Returns a new object of class '<em>Body Params List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body Params List</em>'.
   * @generated
   */
  BodyParamsList createBodyParamsList();

  /**
   * Returns a new object of class '<em>Used Prompts List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Used Prompts List</em>'.
   * @generated
   */
  UsedPromptsList createUsedPromptsList();

  /**
   * Returns a new object of class '<em>Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Context</em>'.
   * @generated
   */
  Context createContext();

  /**
   * Returns a new object of class '<em>Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Request</em>'.
   * @generated
   */
  Request createRequest();

  /**
   * Returns a new object of class '<em>Constraint List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint List</em>'.
   * @generated
   */
  ConstraintList createConstraintList();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns a new object of class '<em>Output Constraint List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Constraint List</em>'.
   * @generated
   */
  OutputConstraintList createOutputConstraintList();

  /**
   * Returns a new object of class '<em>Output Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Constraint</em>'.
   * @generated
   */
  OutputConstraint createOutputConstraint();

  /**
   * Returns a new object of class '<em>External Ref Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>External Ref Param</em>'.
   * @generated
   */
  ExternalRefParam createExternalRefParam();

  /**
   * Returns a new object of class '<em>External Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>External Ref</em>'.
   * @generated
   */
  ExternalRef createExternalRef();

  /**
   * Returns a new object of class '<em>Body Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body Param</em>'.
   * @generated
   */
  BodyParam createBodyParam();

  /**
   * Returns a new object of class '<em>Body Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body Part</em>'.
   * @generated
   */
  BodyPart createBodyPart();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CacherPackage getCacherPackage();

} //CacherFactory
