/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.Constraint#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.disim.cacher.cacher.BodyPart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getConstraint_Body()
   * @model containment="true"
   * @generated
   */
  EList<BodyPart> getBody();

} // Constraint
