/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.Context#getExternal <em>External</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Context#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getContext()
 * @model
 * @generated
 */
public interface Context extends EObject
{
  /**
   * Returns the value of the '<em><b>External</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.disim.cacher.cacher.ExternalRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' containment reference list.
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getContext_External()
   * @model containment="true"
   * @generated
   */
  EList<ExternalRef> getExternal();

  /**
   * Returns the value of the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' attribute.
   * @see #setBody(String)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getContext_Body()
   * @model
   * @generated
   */
  String getBody();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Context#getBody <em>Body</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' attribute.
   * @see #getBody()
   * @generated
   */
  void setBody(String value);

} // Context
