/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Ref Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPname <em>Pname</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPval <em>Pval</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRefParam()
 * @model
 * @generated
 */
public interface ExternalRefParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Pname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pname</em>' attribute.
   * @see #setPname(String)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRefParam_Pname()
   * @model
   * @generated
   */
  String getPname();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPname <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pname</em>' attribute.
   * @see #getPname()
   * @generated
   */
  void setPname(String value);

  /**
   * Returns the value of the '<em><b>Pval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pval</em>' attribute.
   * @see #setPval(String)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRefParam_Pval()
   * @model
   * @generated
   */
  String getPval();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.ExternalRefParam#getPval <em>Pval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pval</em>' attribute.
   * @see #getPval()
   * @generated
   */
  void setPval(String value);

} // ExternalRefParam
