/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.ExternalRef#getPart <em>Part</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.ExternalRef#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRef()
 * @model
 * @generated
 */
public interface ExternalRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Part</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part</em>' reference.
   * @see #setPart(Prompt)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRef_Part()
   * @model
   * @generated
   */
  Prompt getPart();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.ExternalRef#getPart <em>Part</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part</em>' reference.
   * @see #getPart()
   * @generated
   */
  void setPart(Prompt value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.disim.cacher.cacher.ExternalRefParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getExternalRef_Params()
   * @model containment="true"
   * @generated
   */
  EList<ExternalRefParam> getParams();

} // ExternalRef
