/**
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.cacher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prompt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getUsedPrompts <em>Used Prompts</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getBodyParams <em>Body Params</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getContext <em>Context</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getRequest <em>Request</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getPosConst <em>Pos Const</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getNegConst <em>Neg Const</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getDataPresent <em>Data Present</em>}</li>
 *   <li>{@link org.xtext.disim.cacher.cacher.Prompt#getPromptType <em>Prompt Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt()
 * @model
 * @generated
 */
public interface Prompt extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Used Prompts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Used Prompts</em>' containment reference.
   * @see #setUsedPrompts(UsedPromptsList)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_UsedPrompts()
   * @model containment="true"
   * @generated
   */
  UsedPromptsList getUsedPrompts();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getUsedPrompts <em>Used Prompts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Used Prompts</em>' containment reference.
   * @see #getUsedPrompts()
   * @generated
   */
  void setUsedPrompts(UsedPromptsList value);

  /**
   * Returns the value of the '<em><b>Body Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Params</em>' containment reference.
   * @see #setBodyParams(BodyParamsList)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_BodyParams()
   * @model containment="true"
   * @generated
   */
  BodyParamsList getBodyParams();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getBodyParams <em>Body Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body Params</em>' containment reference.
   * @see #getBodyParams()
   * @generated
   */
  void setBodyParams(BodyParamsList value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' containment reference.
   * @see #setContext(Context)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_Context()
   * @model containment="true"
   * @generated
   */
  Context getContext();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getContext <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' containment reference.
   * @see #getContext()
   * @generated
   */
  void setContext(Context value);

  /**
   * Returns the value of the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Request</em>' containment reference.
   * @see #setRequest(Request)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_Request()
   * @model containment="true"
   * @generated
   */
  Request getRequest();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getRequest <em>Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Request</em>' containment reference.
   * @see #getRequest()
   * @generated
   */
  void setRequest(Request value);

  /**
   * Returns the value of the '<em><b>Pos Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos Const</em>' containment reference.
   * @see #setPosConst(ConstraintList)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_PosConst()
   * @model containment="true"
   * @generated
   */
  ConstraintList getPosConst();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getPosConst <em>Pos Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos Const</em>' containment reference.
   * @see #getPosConst()
   * @generated
   */
  void setPosConst(ConstraintList value);

  /**
   * Returns the value of the '<em><b>Neg Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg Const</em>' containment reference.
   * @see #setNegConst(ConstraintList)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_NegConst()
   * @model containment="true"
   * @generated
   */
  ConstraintList getNegConst();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getNegConst <em>Neg Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg Const</em>' containment reference.
   * @see #getNegConst()
   * @generated
   */
  void setNegConst(ConstraintList value);

  /**
   * Returns the value of the '<em><b>Data Present</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Present</em>' containment reference.
   * @see #setDataPresent(OutputConstraintList)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_DataPresent()
   * @model containment="true"
   * @generated
   */
  OutputConstraintList getDataPresent();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getDataPresent <em>Data Present</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Present</em>' containment reference.
   * @see #getDataPresent()
   * @generated
   */
  void setDataPresent(OutputConstraintList value);

  /**
   * Returns the value of the '<em><b>Prompt Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.disim.cacher.cacher.PromptType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prompt Type</em>' attribute.
   * @see org.xtext.disim.cacher.cacher.PromptType
   * @see #setPromptType(PromptType)
   * @see org.xtext.disim.cacher.cacher.CacherPackage#getPrompt_PromptType()
   * @model
   * @generated
   */
  PromptType getPromptType();

  /**
   * Sets the value of the '{@link org.xtext.disim.cacher.cacher.Prompt#getPromptType <em>Prompt Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prompt Type</em>' attribute.
   * @see org.xtext.disim.cacher.cacher.PromptType
   * @see #getPromptType()
   * @generated
   */
  void setPromptType(PromptType value);

} // Prompt
