/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCacherScopeProvider extends DelegatingScopeProvider {
}
