/*
 * generated by Xtext 2.34.0
 */
package org.xtext.disim.cacher.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.disim.cacher.CacherRuntimeModule;
import org.xtext.disim.cacher.CacherStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CacherIdeSetup extends CacherStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CacherRuntimeModule(), new CacherIdeModule()));
	}
	
}
